### PR TITLE
Add clarity to fee credit

### PR DESCRIPTION
**Pull request by exu3**

### CODE REVIEW

**Comment by maxwofford** [comment]
Screen Shot 2022-09-29 at 15 14 30

^ Current UI I see on the preview deploy

This looks great! Feel free to assign once it's ready to review. Maybe we can include a small info icon too next to the credit wording so I know I can hover it on mobile?

**Comment by cjdenio** [comment]
Also tooltips don't work on mobile— maybe this should be part of the modal that pops up when you click "Pending fees"?

**Comment by maxwofford** [comment]
Love this! What needs to happen for this to merge?

**Comment by maxwofford** [comment]
Merging with confirmation from @exu3 over Slack!

**Pull request merged**
