### PR TITLE
Make the telephone in the footer a link

### PR DESCRIPTION
**Pull request by sampoder**
hi hi, so uhh I thought I'd make a pr coz I thought this would be a nice thing to add, hope you all are cool with this 😁

### CODE REVIEW

**Comment by sampoder** [comment]
oh also, I dont know ruby at all but im guessing this is how it works ¯\_(ツ)_/¯

**Comment by maxwofford** [comment]
Good start, but you should check the arguments `link_to` takes

Screen Shot 2020-11-09 at 10 14 30 AM

Check out the preview link to see what it looks like!

**Comment by sampoder** [comment]
ayyy!!! it worked

**Review by maxwofford — APPROVED** [review]

**Comment by maxwofford** [comment]
Can confirm this is working the way it should on the preview deploy

**Pull request merged**
