### PR TITLE
Try upgrading to heroku-22 for review apps

### PR DESCRIPTION
**Pull request by albertchae**
Now that we're on ruby 3.1, we can try upgrading to heroku-22 for review apps. After confirming the app works ok on 22, we can change it for production as well.

https://devcenter.heroku.com/articles/heroku-22-stack

https://devcenter.heroku.com/articles/ruby-support#ruby-versions

We can remove 2 buildpacks we were using for heroku-20:

It looks like the heroku-22 built in imagemagick is technically older than what the buildpack was giving us, but it has HEIC support and so HEIC conversion works without an explicit buildpack.

heroku-20 with buildpack
```
$ convert -version
Version: ImageMagick 7.0.11-5 Q16 x86_64 2021-03-20 https://imagemagick.org/
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib djvu fontconfig freetype heic jbig jng jpeg lcms lqr lzma openexr pangocairo png tiff x xml zip zlib
```

heroku-22 no buildpack
```
$ convert -v
Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org/
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

We can remove our custom buildpack for poppler 21.03.0 that we introduced in https://github.com/hackclub/bank/pull/3395, because heroku-22 has poppler 22.02.0 installed by default

```
$ pdftoppm -v
pdftoppm version 22.02.0
Copyright 2005-2022 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

### CODE REVIEW

**Comment by albertchae** [comment]
Got held up by issues with heroku review apps running out of memory, but I still want to verify if the imagemagick included with heroku-22 can convert heic correctly

**Comment by albertchae** [comment]
verified that heic conversion works without a special buildpack now
image

**Comment by albertchae** [comment]
@maxwofford can you have someone go through the [review app for this PR](https://bank-hackclu-upgrade-he-4alo5w.herokuapp.com) and see if they notice any bugs (besides the 500s for out of memory due to lower spec review apps)? Once we feel good about this, we should turn it on in prod also and we can archive https://github.com/hackclub/heroku-buildpack-poppler

**Review by maxwofford — APPROVED** [review]
This is behaving correctly for me. I uploaded PDFs and user avatars in staging.

**Comment by maxwofford** [comment]
Quick tl;dr for others on @hackclub/bank-engineering – this won't affect prod, but will affect other preview deploys. Let me know if your preview deploys are failing to do image generation or resizing because that might be caused by this change.

**Pull request merged**
