### PR TITLE
StatsD: Measure Stripe webhook execution duration

### PR DESCRIPTION
**Pull request by garyhtou**
This measurement won't be entirely accurate since it only measures the "business logic" portion of the request, however, it'll allow us to track any increases in request durations.

### CODE REVIEW

**Comment by garyhtou** [comment]
@maxwofford after this is merged, what do we need to do to get this into a graph on Grafana?

**Review by maxwofford — APPROVED** [review]
Setup an account for telemetry in #hq-engineering on slack and then you can make a dashboard!

**Comment by garyhtou** [comment]
@maxwofford we've had a handful of webhooks since merge, however, it seems like grafana isn't picking anything up. I expect it under `stats.production.hcb.StripeController.*`

image

**Comment by maxwofford** [comment]
Hmmmm... that's where I'd expect to see it too. What if you [add something like](https://github.com/hackclub/hcb/blob/227b288aafe87ecbfc501bc15f25e56542ae28c3/config/initializers/statsd.rb#L11) `StatsD.increment("stripe_controller.#{method}", 1)` just to check that the line is running?

**Comment by garyhtou** [comment]
Nevermind! I found it under the `timers` namespace.

`stats.timers.production.hcb.StripeController`

https://github.com/statsd/statsd/blob/master/docs/namespacing.md

**Pull request merged**
