### PR TITLE
GitHub Actions: RuboCop Autocorrect Offenses

### PR DESCRIPTION
**Pull request by garyhtou**
Our GitHub Actions workflow will now create a commit with autocorrections for RuboCop offenses

### CODE REVIEW

**Comment by garyhtou** [comment]
heck yeah! looks like it's working

**Comment by cjdenio** [comment]
Thoughts on making this a local commit hook? That way we don't have a bunch of bot commits

**Comment by garyhtou** [comment]
> Thoughts on making this a local commit hook? That way we don't have a bunch of bot commits

@cjdenio what are your thoughts on @mentioning a bot to have it pus and autofix commit?

for example: @hackclub-bot rubocop

**Comment by garyhtou** [comment]
closing as satle as part of triage call on 6/23/2023

**Pull request closed without merging**
