### PR TITLE
[User Roles] Don't let people change their own roles

### PR DESCRIPTION
**Pull request by malted**
image

Admins can still change their own roles because nowt really changes

### CODE REVIEW

**Comment by sampoder** [comment]
Left Side is my favourite manager!

**Comment by garyhtou** [comment]
What if we hide the dropdown and the `v` icon? that would remove the need for a tooltip

**Comment by malted** [comment]
Done!

**Review by garyhtou — APPROVED** [review]
policy is good! just one comment about renaming

**Pull request merged**
