### PR TITLE
Make name validation work properly during onboarding

### PR DESCRIPTION
**Pull request by cjdenio**
Updates the username validation to only fail if
- The name is blank AND
- The name was not blank previously

(fixes #2449)

### CODE REVIEW

**Comment by maxwofford** [comment]
Does this handle the case a user sets their name during onboarding, then tries to blank out their name?

**Comment by cjdenio** [comment]
Yep, it'll fail if the user tries to go from `"Caleb"` -> `nil`

(but `nil` -> `nil` is allowed)

**Review by maxwofford — APPROVED** [review]
Awesome! If this works in staging & you can create a new account that goes through the onboarding just fine, go for merge!

**Comment by cjdenio** [comment]
It works!

For posterity, this also still prevents users from removing their own name:

Screen Shot 2022-04-10 at 6 06 33 PM

**Pull request merged**
