### PR TITLE
Remove `has_fiscal_sponsorship_document` boolean

### PR DESCRIPTION
**Pull request by garyhtou**

### CODE REVIEW

**Comment by motdotla** [comment]
hey, @garyhtou, can you resolve conflicts on this one when you get a chance?

**Comment by garyhtou** [comment]
yup! is it good to merge after resolving? (I think it won't save the resolved edits unless it's merged)
image

**Comment by motdotla** [comment]
@garyhtou you just need to click 'commit merge' at the top right

**Comment by garyhtou** [comment]
ah okay, there we go. thanks!

**Pull request merged**
