### PR TITLE
Update receipt upload button

### PR DESCRIPTION
**Pull request by cjdenio**
This PR updates the transaction page to better match the new `/attach_receipt` page.

I'm not totally set on the design– I know @maxwofford wasn't sure about how the width of the card looked.

Screen Shot 2022-05-13 at 10 26 08 PM

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Love it– this layout feels nice. LGTM!

**Review by exu3 — APPROVED** [review]
Looks good to me!

---

Would it make sense to make the wording on the upload buttons on the hcb code show page & attach_receipt page the same? 
Screen Shot 2022-05-15 at 09 01 38

**Comment by cjdenio** [comment]
@exu3 Good point, though I think "Upload receipt" is better for the transaction page; otherwise it isn't clear _what_ the user is uploading a photo for. (that isn't an issue on the `attach_receipt` page)

###### ~"Upload your cat photos here." Possible easter egg idea?~

**Comment by exu3** [comment]
Yes Cat!!111!!1!!

**Pull request merged**
