### PR TITLE
Drop mini_racer

### PR DESCRIPTION
**Pull request by northeastprince**
I don't this will affect anything, but from what I gather, it was never really needed in the first place?

### CODE REVIEW

**Comment by northeastprince** [comment]
.deploy atm1

**Review by maxwofford — APPROVED** [review]
Let's go ahead and merge this in!

**Comment by maxwofford** [comment]
I'm merging this with the understanding that there may be some issues with our react components that didn't show up when testing this locally. All our react components are non-critical to the app so we can revert this if there are UI bugs that start showing up.

**Comment by albertchae** [comment]
hooray, goodbye mini 🏎️

**Pull request merged**
