### PR TITLE
SUP welcome mailer

### PR DESCRIPTION
**Pull request by garyhtou**
#2219

https://hackclub.slack.com/archives/C026RKHLPNJ/p1643223525047800?thread_ts=1642749949.024700&cid=C026RKHLPNJ

### CODE REVIEW

**Comment by maxwofford** [comment]
Going through triage for PRs– what's the status on this?

**Comment by exu3** [comment]
I believe this is good to close since the accepted/rejected emails for Sups
will be done manually.

**Comment by maxwofford** [comment]
@exu3 Cool–closing. I think @hackliv wanted a button (`mailto:`) that would open an email already templated to the applicants. Is that tracked anywhere?

**Comment by exu3** [comment]
> a button (mailto:) that would open an email already templated to the applicants. Is that tracked anywhere

Yep, that's one of the action items for #2206

**Pull request closed without merging**
