### PR TITLE
Receipts: Extract textual contents of PDFs

### PR DESCRIPTION
**Pull request by garyhtou**
Extracts the text from Receipt PDFs

After backfilling data (ran as a test in development, using production data), the database size increased by 24.89 MB (from 1.42 GB to 1.45 GB). Out of the 18.5k receipts about half of them are PDFs (see https://github.com/hackclub/bank/issues/3765#issuecomment-1500792029). 9k PDF receipts were successfully backfilled with textual content and 383 errored or resulted in no textual content.

Oh yeah, it takes a while too (35 mins on my computer):
```
Real Time: 2054.1484909770006
Total: 305.589875
User: 229.374499
System: 76.21537599999999
```

---

Known Issues (with Poppler)

- Raises `ArgumentError: string contains null byte` when extracting text content from IWANTMYNAME's invoices
	- ex. https://bank.hackclub.com/hcb/MNHp6q
	- I've suppressed these errors

### CODE REVIEW

**Comment by garyhtou** [comment]
heroku ain't too happy
```
       Fetching cairo-gobject 4.1.2
       Installing cairo-gobject 4.1.2 with native extensions
       Fetching gio2 4.1.2
       Installing gio2 4.1.2 with native extensions
       Fetching poppler 4.1.2
       Installing poppler 4.1.2 with native extensions
       Bundle complete! 114 Gemfile dependencies, 271 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Post-install message from httparty:
       When you HTTParty, you must party hard!
       Bundle completed (230.35s)
       Cleaning up the bundler cache.
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'Poppler' (any version) not found
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.1.2/lib/gobject-introspection/loader.rb:40:in `require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.1.2/lib/gobject-introspection/loader.rb:40:in `load'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/poppler-4.1.2/lib/poppler.rb:27:in `<module:Poppler>'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/poppler-4.1.2/lib/poppler.rb:22:in `<main>'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `each'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `block in require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `each'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `require'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler.rb:186:in `require'
 !     /tmp/build_7d2d9e7d/config/application.rb:9:in `<main>'
 !     /tmp/build_7d2d9e7d/Rakefile:6:in `require_relative'
 !     /tmp/build_7d2d9e7d/Rakefile:6:in `<main>'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
 !     /tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
 !     /tmp/build_7d2d9e7d/bin/rake:6:in `<main>'
 !
/tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
rake aborted!
GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'Poppler' (any version) not found
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.1.2/lib/gobject-introspection/loader.rb:40:in `require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.1.2/lib/gobject-introspection/loader.rb:40:in `load'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/poppler-4.1.2/lib/poppler.rb:27:in `<module:Poppler>'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/poppler-4.1.2/lib/poppler.rb:22:in `<main>'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `each'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `block in require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `each'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `require'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.25/lib/bundler.rb:186:in `require'
/tmp/build_7d2d9e7d/config/application.rb:9:in `<main>'
/tmp/build_7d2d9e7d/Rakefile:6:in `require_relative'
/tmp/build_7d2d9e7d/Rakefile:6:in `<main>'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/tmp/build_7d2d9e7d/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/tmp/build_7d2d9e7d/bin/rake:6:in `<main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:967:in `rake'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:69:in `block in run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:63:in `run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:103:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:988:in `allow_git'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

```

**Review by YodaLightsabr — APPROVED** [review]
This looks good!

**Comment by garyhtou** [comment]
@albertchae would you mind taking a look at this? I'm trying to get this to build on Heroku. It builds and runs fine locally (Docker), but fails on Heroku (likely due to build packs)

There was a build issue on GitHub Actions that was fixed by this commit (https://github.com/hackclub/bank/pull/3769/commits/2f0cb1e2450bcb8834f6599cb135ac8cd5fec613).

I experimented with [`5d39d05` (#3769)](https://github.com/hackclub/bank/pull/3769/commits/5d39d05ef84874faceb1b6e15777873ed9627556) and [`017a94a` (#3769)](https://github.com/hackclub/bank/pull/3769/commits/017a94a0882aa853aa263c5fe948c4519d686a2f) to try to get Heroku to build (no success). And have run into a few different build errors including https://github.com/hackclub/bank/pull/3769#issuecomment-1500848628

**Comment by albertchae** [comment]
@garyhtou ah yeah I'll look into this. I did set up a custom poppler buildpack for heroku which might be causing you issues actually.

**Comment by albertchae** [comment]
@garyhtou ok wow, that was more of a puzzle than I thought, but I finally have a PR into this branch that fixes the build here https://github.com/hackclub/bank/pull/3836.

The biggest gotcha was that you shouldn't set the environment variable through heroku settings or app.json because it overrides what's in the apt fork, which unfortunately has been an open PR against heroku master for years without any review... I also think it might be worth making a hackclub fork that is more recent so that we can continue to have comments in the `Aptfile`

**Comment by garyhtou** [comment]
Yay! Successfully backfilled 9,349/19,582 receipts in production. This is a good number since roughly only half of the receipts are PDFs, so we that means we were able to extract the textual context of most PDF receipts! (see pr description above)

**Comment by garyhtou** [comment]
receipts are also being async processed on upload!

image

**Pull request merged**
