### PR TITLE
Hide the bottom navigation section in Transparency Mode

### PR DESCRIPTION
**Pull request by devramsean0**
## Summary of the problem

Hides the entire bottom section on the nav bar when in transparency mode

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
rewritten to include the entire section

**Comment by malted** [comment]
FYI, since Gary created the issue you're referencing, I merged my user perm PR which blurs a faker email in the pending invites section. I really prefer this over hiding the section entirely.
image

**Comment by garyhtou** [comment]
Hi! I'm confused by this PR.

Looking at the PR title and first commit, it appears that the goal was to hide the invite section at the bottom of the team page. However, looking at the final code in this PR, it appears to instead be hiding some navigation items.

Can you update either the PR title/description or the code so that the two align with each other?

Also, if there's an associated issue, please link it!

**Comment by garyhtou** [comment]
> FYI, since Gary created the issue you're referencing, I merged my user perm PR which blurs a faker email in the pending invites section. I really prefer this over hiding the section entirely. image

@malted the blur is so cool! I think we chatted about this a little bit in SF. I've given this some thought— although the pending invitations section is a nice touch (especially with the fake email blur), it doesn't provide any useful information from the perspective of someone viewing it in transparency mode. I would opt to remove the section in transparency mode.

**Comment by garyhtou** [comment]
superseded by https://github.com/hackclub/hcb/pull/5199

I think that other PR does what we want. This PR doesn't solve https://github.com/hackclub/hcb/issues/5379

**Pull request closed without merging**
