### PR TITLE
Add TXT Record Verification for Google Workspace Domain Requests

### PR DESCRIPTION
**Pull request by kunalbotla**
many users have submitted domains that they don't actually own. this PR adds a simple TXT record for the user to add so that we can confirm their ownership before approving for it to add to Google Workspace. this prevents dormant domains and requests for unregistered domains as well as counting towards our Google Workspace domain limits.

### CODE REVIEW

**Comment by garyhtou** [comment]
Do domains count against our limit even when Hack Club doesn't have verified ownerships? (through the verification token)

**Comment by kunalbotla** [comment]
I believe so; figuring out if they own their domain is also complicated at the moment

**Comment by kunalbotla** [comment]
@garyhtou could you take a look at why going to the Google Workspace page is throwing an error? I tried making a few changes of how it's formatted and it didn't seem to fix it, and it's using the same format as the existing DNS table.

**Comment by kunalbotla** [comment]
thanks for building that generation and check system out! i was going with a manual verification system lol

**Comment by maxwofford** [comment]
@kunalbotla I've just skimmed this and I'm super excited to try out this feature. I'm getting an error when I try to open the Google Workspace page for orgs (just tested with orgs 1236 & 386). Can you get it to the point I can go through the domain verification flow and feel it for myself? Once it's there, please tag me back in!

**Comment by maxwofford** [comment]
Also, [linking this](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F175747%3Fhl%3Den&product_context=175747&product_name=UnuFlow&trigger_context=a) for posterity 
Screen Shot 2022-01-14 at 01 40 34

**Comment by cjdenio** [comment]
This looks stale so closing for now.

**Pull request closed without merging**
