### PR TITLE
Fix heading centering & small design improvements v2

### PR DESCRIPTION
**Pull request by lachlanjc**
- Fix centering of event name on event show pages, closes #449 (closed previously by reverted PR)
- Show settings/manage team links in overflow menu
- Improve menu + dock designs, especially on mobile

### CODE REVIEW

**Comment by tmb** [comment]
can you get screenshots of the changed stuff?

**Comment by lachlanjc** [comment]
Yeah, it’s the same as #453 @tmb

**Review by maxwofford — APPROVED** [review]
Oh, love the button changes on this. In the weeds rn on unborking checks, so I approve the design changes & trust you've tested it.

**Comment by maxwofford** [comment]
@lachlanjc go ahead and merge if you're ready

**Comment by lachlanjc** [comment]
@maxwofford Our Heroku preview deploys don’t seem to be working—any ideas what’s up? Would like to check this isn’t broken without figuring out how to set up my dev env again

**Comment by maxwofford** [comment]
Yeah, review apps only run for so long. This PR has probably been open too long. One option is to open a new PR in a new branch...

**Comment by lachlanjc** [comment]
Will try it, thanks

**Pull request closed without merging**
