### PR TITLE
[Appsignal] Configure Logger

### PR DESCRIPTION
**Pull request by sampoder**
Closes https://github.com/hackclub/hcb/issues/4893. Can someone sanity check this?

### CODE REVIEW

**Comment by sampoder** [comment]
@northeastprince you know this stuff pretty well, could you help check this for me?

**Comment by northeastprince** [comment]
We should probably be using lograge.

https://github.com/hackclub/hackathons-backend/pull/133
https://github.com/hackclub/hackathons-backend/pull/204

**Comment by sampoder** [comment]
Sweet

**Comment by sampoder** [comment]
How does this look to you?

**Comment by northeastprince** [comment]
Good - you might wanna add user ID or other tags though.

**Pull request merged**
