### PR TITLE
Add share button to donation link

### PR DESCRIPTION
**Pull request by manuthecoder**
This PR adds a native share button to a prefilled amount donation link

image
image

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Screenshot 2024-07-10 at 10 07 39 AM

Do all browsers support this? I'm getting these errors.

**Comment by manu-gurudath** [comment]
MDN reports functionality for most browsers except Firefox

**Comment by manu-gurudath** [comment]
Maybe we could just hide the button on Firefox

**Comment by sampoder** [comment]
I got this error on Chrome

**Comment by cjdenio** [comment]
It's only supported on Windows and ChromeOS

**Pull request closed without merging**
