### PR TITLE
Redesign pinned transactions

### PR DESCRIPTION
**Pull request by lachlanjc**
## Summary of the problem

Pinned transactions using the grey color are very visually heavy, and don't size to fit the container:
image

## Describe your changes

Using white & reducing boldness reduces the visual weight, and now they fit the container dynamically:
image

I've switched to an unpin icon that's more visually descriptive:
CleanShot 2024-05-15 at 23 35 40@2x

On mobile, they stack horizontally, with scroll snapping:
Hackpenn on iPhone 12 Pro

(You can see that headings are no longer forced to be in column wrapping too on mobile now.)

### CODE REVIEW

**Review by sampoder — DISMISSED** [review]
Looks great, thank you!

**Comment by sampoder** [comment]
@manuthecoder feel free to chime in with thoughts!

**Review by garyhtou — DISMISSED** [review]
I love it!

**Comment by garyhtou** [comment]
Go ahead and merge when ready

**Comment by manu-gurudath** [comment]
Looks great to me!

**Review by garyhtou — APPROVED** [review]

**Pull request merged**
