### PR TITLE
Org Ledger: Rename filter tabs

### PR DESCRIPTION
**Pull request by rluodev**
done as gary asked

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]

**Review by sampoder — COMMENTED** [review]
Tags on L59 also needs to be changed FYI :D

**Review by garyhtou — APPROVED** [review]
ty

**Review by sampoder — APPROVED** [review]
👍 Does what it says on the tin

**Comment by garyhtou** [comment]
Group 1

**Comment by sampoder** [comment]
Exactly

**Pull request merged**
