### PR TITLE
Prevent new Sticker Mule applications

### PR DESCRIPTION
**Pull request by garyhtou**
We currently have an issue where all of our sticker mule promo codes are expired. Going to prevent new applications until we have this figured out.

The Airtable form has been password protected to prevent new submissions. I wanted to add this message on Bank so that it wasn't confusing.

### CODE REVIEW

**Comment by maxwofford** [comment]
Great start, maybe shorten the button's word -- currently getting trimmed

image

**Review by maxwofford — APPROVED** [review]

**Comment by maxwofford** [comment]
Just approved so you can merge after fixing that

**Comment by maxwofford** [comment]
Merging for the sake of time

**Comment by garyhtou** [comment]
Good catch! I took a look at it last night but couldn't think of a shorter word

**Pull request merged**
