### PR TITLE
Fix emburse notifications

### PR DESCRIPTION
**Pull request by tmb**
⚠️ BEFORE EMBURSE TRANSACTION JOB IS RUN ON PRODUCTION AGAIN AFTER MERGE: `EmburseTransaction.all.each {|e| e.update!(notified_user_at: Time.now)}` (make sure to migrate first!) ⚠️ 

This fixes my previous PR from the Emburse email notification branch.

### CODE REVIEW

**Comment by maxwofford** [comment]
@tmb what if you run this in the migration?

**Comment by tmb** [comment]
@zachlatta: ping!

**Comment by lachlanjc** [comment]
@tmb Can you resolve the merge conflict here?

**Comment by maxwofford** [comment]
@lachlanjc: I don't realistically have the capacity to review & test this is a timely manner. I'm fine with this so long as it works

**Comment by maxwofford** [comment]
Skimming over the code here, this line looks fishy: https://github.com/hackclub/bank/pull/77/files#diff-e766a0a3b6ed325565aee6a7bc50d0e8R3

**Comment by tmb** [comment]
@MaxWofford that's there in case we rename EmburseTransaction down the road so that the migration can still be performed. (I got it from [this](https://railsguides.net/change-data-in-migrations-like-a-boss/) guide that zrl linked me to)

**Comment by lachlanjc** [comment]
@tmb What’s happening here?

**Comment by tmb** [comment]
closing because this was from Jan and I have no idea what I was doing.

**Pull request closed without merging**
