### PR TITLE
Add example resource page

### PR DESCRIPTION
**Pull request by maxwofford**
PR created for preview deploy, please don't merge

### CODE REVIEW

**Comment by exu3** [comment]
ooooweeee rick, thanks max!

**Comment by exu3** [comment]
is the page supposed to be accessible through here https://bank--pr-1822.herokuapp.com/devhacks-test-event/resources? i can't seem to find it there

**Comment by maxwofford** [comment]
ooooowwweeee, look at me! looks like i made a typo

**Comment by maxwofford** [comment]
Closing this example b/c https://github.com/hackclub/bank/pull/1853 was opened

**Pull request closed without merging**
