### PR TITLE
Update icon set (@hackclub/icons)

### PR DESCRIPTION
**Pull request by garyhtou**
Our icon set is now up to date with https://github.com/hackclub/icons and still includes some one-off icons unique to Bank.

https://github.com/hackclub/icons-for-bank
^ that's the repo i used to do some sketchy icon set comparsion
Deployed version: https://icons-for-bank.hackclub.dev/

---

Summary of process:

1. Import & overwrite (except `admin-badge` and `view-forward`
2. Remove duplicates and update their references
3. remove outdated, unused, and broken icons
4. fix svg errors

### CODE REVIEW

**Comment by exu3** [comment]
Epic, thanks so much Gary! I noticed this with the sessions table PR.

**Comment by garyhtou** [comment]
> Epic, thanks so much Gary! I noticed this with the sessions table PR.

Np!!! we can never have enough icons :)

**Comment by garyhtou** [comment]
~~TODO: 'notification' and 'bell' are duplicates~~ DONE

**Review by exu3 — APPROVED** [review]
I think it looks good!

**Comment by garyhtou** [comment]
Thanks @eilla1!

**Comment by garyhtou** [comment]
I would prefer to remove the styling from these two icons' SVG (and apply it when we use the icons). but that can happen in the future

image
image

**Pull request merged**
