### PR TITLE
OAuth authorization: allow overriding color scheme via query param

### PR DESCRIPTION
**Pull request by cjdenio**
worthwhile feature

### CODE REVIEW

**Review by garyhtou — COMMENTED** [review]
maybe move this into a controller concern?

**Comment by cjdenio** [comment]
The thing is: the controller for this is defined by a gem and can't easily be modified

**Comment by garyhtou** [comment]
it's a bit of work, but i think this might work.

https://doorkeeper.gitbook.io/guides/configuration/other-configurations#custom-controllers

```ruby
class RespectThemeParam
  extend ActiveSupport::Concern
  included do
    before_action do
      # code
    end
  end
end
```

```ruby
class DoorkeeperController < ActionController::Base
  include RespectThemeParam
end
```

```ruby
Doorkeeper.configure do
  base_controller 'DoorkeeperController'
end
```

you can also totally skip the concern, but i think it might be nice because we likely will want to reuse this logic elsewhere.

**Comment by garyhtou** [comment]
Or, the easier, but janky (and not recommended solution) is to reopen the `Doorkeeper::ApplicationController` class.

```ruby
class Doorkeeper::ApplicationController
  include RespectThemeParam
end

**Pull request merged**
