### PR TITLE
Increase Contrast on Feedback Form Button

### PR DESCRIPTION
**Pull request by sampoder**
At times, the feedback form being very opaque can make it blend into other parts of the UI:

Screenshot 2023-08-28 at 10 41 01 AM

This PR increases the contrast:

Screenshot 2023-08-28 at 10 41 56 AM

### CODE REVIEW

**Comment by maxwofford** [comment]
cc @hackliv

**Comment by hackliv** [comment]
lol yes!

**Comment by cjdenio** [comment]
er now it looks weird in dark mode:

Screenshot 2023-08-28 at 10 44 16 PM

**Comment by sampoder** [comment]
Oh that's weird.... I'll fix it tonight

**Pull request merged**
