### PR TITLE
Adjust z-index on the filter bar

### PR DESCRIPTION
**Pull request by clarencejychan**
Fixes #1917 #1155

image

### CODE REVIEW

**Comment by clarencejychan** [comment]
Didn't see the related issue someone commented. Looking at those, but a bit trickier.

**Comment by exu3** [comment]
When I hover over the filter bar, the cursor doesn't change into the text-input cursor / can't type stuff into the filter bar

https://user-images.githubusercontent.com/72365100/139623619-227cb172-8984-4d12-bd4f-36cfe1924146.mov

**Comment by clarencejychan** [comment]
https://user-images.githubusercontent.com/14989024/139624833-e6513977-3eda-4e4c-a8e0-064972fbcee6.mp4

**Comment by clarencejychan** [comment]
Should be addressed now and should work for all content so there won't be any one-off fixes required (see #1155)

**Review by maxwofford — APPROVED** [review]
This looks great! Go ahead and rebase then merge!

**Comment by maxwofford** [comment]
Nvm, looks like I can rebase on my end

**Pull request merged**
