### PR TITLE
[782] Add link to business intelligence tool

### PR DESCRIPTION
**Pull request by motdotla**
https://github.com/hackclub/bank/issues/782

Screen Shot 2020-08-20 at 11 16 25 AM

### CODE REVIEW

**Comment by lachlanjc** [comment]
Awesome. Should all the pages/graphs be saying Internal Server Error on the preview deploy?

**Comment by motdotla** [comment]
That is because migrations have not been run I believe. What's the process there you guys like to do? I could make migrations run automatically on preview deploys.

**Comment by motdotla** [comment]
ah, actually it also might be the ENV settings for preview deploys. updating.

**Comment by lachlanjc** [comment]
That’d be awesome actually—preview deploys would be so much more useful if they ran migrations

**Comment by motdotla** [comment]
Ok, fixed up and migrations run automatically now. https://bank-hackclu-782-link-t-gjn5fo.herokuapp.com/blazer

If you ever want to change that you can do so here: https://dashboard.heroku.com/pipelines/e61db6c3-496d-4233-ad3c-4a29752dcc12/settings

just change to 'true'

Screen Shot 2020-08-20 at 11 38 00 AM

**Comment by lachlanjc** [comment]
Thank you!! I'm still getting the 500 errors, but if it'll work in production, go ahead & merge

**Review by lachlanjc — APPROVED** [review]

**Pull request merged**
