### PR TITLE
Organization header redesign

### PR DESCRIPTION
**Pull request by cjdenio**
- Limited avatar list to 5 avatars. Helps a lot especially on mobile
- Moved "Pending fees" to the top of the transaction list
- Updated balance in UI to reflect actual available balance (including pending fees)

<table>
<tr>
	<td> Screenshot 2023-01-09 at 3 47 50 PM
    <td> 
</table>

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
looking good!

**Review by exu3 — APPROVED** [review]
These changes look great!

**Review by maxwofford — APPROVED** [review]
Thanks for adding this! LGTM

**Comment by cjdenio** [comment]
yee haw!

**Pull request merged**
