### PR TITLE
Fix workflow syntax for MRSK branch deploys

### PR DESCRIPTION
**Pull request by northeastprince**
💀

### CODE REVIEW

**Comment by northeastprince** [comment]
.deploy

**Comment by northeastprince** [comment]
Ok, seems like the Action error is pointing to the double quotes, and the example in the repo shows single quotes, so this should fix it once merged..

**Review by maxwofford — APPROVED** [review]
Lmao, weird they don't accept that. LGTM!

**Comment by northeastprince** [comment]
.deploy noop

**Comment by northeastprince** [comment]
failure came from Checkout - restoring and trying again

**Comment by northeastprince** [comment]
.deploy noop

**Comment by northeastprince** [comment]
...

**Comment by northeastprince** [comment]
.deploy noop

**Comment by northeastprince** [comment]
fingers crossed...

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
invalid reference to target in workflow, fixing in #3651 - ah, the joys of having to test in `main`...

**Pull request merged**
