### PR TITLE
✨ Add egestion endpoints

### PR DESCRIPTION
**Pull request by malted**

### CODE REVIEW

**Comment by maxwofford** [comment]
@malted @grymmy before we actually merge anything in that allows production data out, I'd like to do a quick security review of where this is being stored etc.

**Comment by malted** [comment]
Did not request this review, please ignore for now

**Comment by garyhtou** [comment]
@malted after you squash the bugs with User Permissions, let's continue our chat about handling all the data dashboard stuff in Ruby!

Would you mind if we closed this PR?

**Comment by malted** [comment]
Closing for now.

**Pull request closed without merging**
