### PR TITLE
Move error pages back to Rails' public/* solution

### PR DESCRIPTION
**Pull request by northeastprince**
There is no reason as of now to use a controller and custom logic to render error pages.

### CODE REVIEW

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
Seems to be working fine on atm1, so I assume the deployment failure is the build size.

**Comment by northeastprince** [comment]
I basically just copied the existing error pages and some stuff from CSS files and modified them to reflect the absence of the asset pipeline with the standalone HTML files.

**Comment by maxwofford** [comment]
This looks like a visual regression– the error pages used to look like this:
Screenshot 2023-03-21 at 12 21 15

Now they look like this:
Screenshot 2023-03-21 at 12 20 52

**Comment by maxwofford** [comment]
I'd like to graciously fallback to static but still attempt to render dynamic stuff. Removing the custom controller logic helps people loading with the wrong file extension (a small number) but currently is a worse experience for anyone who runs into an error page (a larger number of users).

**Comment by garyhtou** [comment]
hey @northeastprince just checking in here. are we blocking here?

**Comment by garyhtou** [comment]
@northeastprince fyi, closing as stale. feel free to open

**Pull request closed without merging**
