### PR TITLE
Update brand guidelines

### PR DESCRIPTION
**Pull request by rluodev**
If possible, please add to /newbrandguidelines slug.

### CODE REVIEW

**Comment by rluodev** [comment]
i might probs actually just write the page on my own

**Comment by garyhtou** [comment]
Hey Ruien! Yay!! it's exciting to see your first pr :)

I like that we're adding a branding guideline. Bank currently doesn't support rending MDX, however, we've got a couple of options here.

- We can try to add MDX rendering to Bank, however, that will likely be a heavy project.
- Alternatively, we can change the MDX over to ERB. this is how all of Bank's pages are rendered. See the "receive checks" page as an example.
	- https://bank.hackclub.com/hq/receive_check
	- https://github.com/hackclub/bank/blob/fe98602e76f6747961b8914a572e963970873002/app/views/events/receive_check.html.erb

**Comment by rluodev** [comment]
Yeah I think erb might work; not too familiar with ruby myself though

**Comment by garyhtou** [comment]
> Yeah I think erb might work; not too familiar with ruby myself though

It's all good! If you'd like to give it a shot, feel free to do so. Either way, let me know if you'd like some help

**Comment by northeastprince** [comment]
The work that I'm doing in #3707 (once complete) should provide the core domain models necessary for all types of authoritative content from the Bank team (not just major announcements - small updates, tips, guidelines, news, etc.), which could be used for this too. And it'll have a rich text editor on the admin side so we don't have to write markdown or hardcode HTML!

**Comment by rluodev** [comment]
> > Yeah I think erb might work; not too familiar with ruby myself though
> 
> It's all good! If you'd like to give it a shot, feel free to do so. Either way, let me know if you'd like some help

Yeah I think I might need some help - I've never been particularly good with frontend stuff

**Comment by garyhtou** [comment]
@ma1ted would you like to help out here?

**Comment by malted** [comment]
> @ma1ted would you like to help out here?

Would love to! I'll have a look in a few.

**Comment by rluodev** [comment]
thanks! BTW FYI the sample webpage I setup is at hcbbrandguidelines.hackclub.dev and the password is HCBBGDraftPreview to access it. Mainly that's just how I want the callout boxes to look.

**Review by MelSmith104 — COMMENTED** [review]
In the bank accounts sections please list Increase first.

**Comment by rluodev** [comment]
> In the bank accounts sections please list Increase first.

Done!

**Comment by hackliv** [comment]
@maxwofford, what're your thoughts on whether to include the do's/don'ts at the top vs bottom? My thoughts were that putting it at the bottom would allow people to read through other important stuff first and then have a cheat sheet as a reminder at the end. Did you think it would be better at the top?

**Comment by malted** [comment]
I'm looking at integrating `mdx` support into bank; once signup stuff is merged I'll start on that

**Comment by rluodev** [comment]
@ma1ted Btw just a quick followup on this; when roughly should this have a testable MVP?

**Comment by hackliv** [comment]
> @maxwofford, what're your thoughts on whether to include the do's/don'ts at the top vs bottom? My thoughts were that putting it at the bottom would allow people to read through other important stuff first and then have a cheat sheet as a reminder at the end. Did you think it would be better at the top?

hey @maxwofford just wondering your thoughts on this!

**Comment by malted** [comment]
> @ma1ted Btw just a quick followup on this; when roughly should this have a testable MVP?

Ever since I deleted my branch after merging my work my codespace has been messed up; haven't forgotten about this!

**Comment by hackliv** [comment]
Hey! Are there updates on when we can get this merged :D

**Comment by rluodev** [comment]
@ma1ted just pinging on this again!

**Comment by northeastprince** [comment]
I'm working on #3707 which should help with adding branding guidelines and any other resources. I think we should avoid trying to interpolate a separate language when we have existing solutions in Rails like [Action Text](https://guides.rubyonrails.org/action_text_overview.html).

**Review by maxwofford — APPROVED** [review]
Looking good! Can you make sure the ERBLint passes, then you're good to merge!

**Review by hackliv — APPROVED** [review]
🎉

**Pull request merged**
