### PR TITLE
Interface Instances of `Docusign` → `DocuSign`

### PR DESCRIPTION
**Pull request by kunalbotla**
there are instances of "DocuSign" being [incorrectly capitalized](https://www.docusign.com/IP/trademark-brand-guide) as "Docusign" in user & admin-facing pages. this PR changes those instances. this doesn't impact any controllers

### CODE REVIEW

**Comment by kunalbotla** [comment]
I'm getting an error on Zeitwerk's check. I'm not sure if this is an error with the code itself or the check since it should be expecting `DocuSignController` now

image

**Comment by cjdenio** [comment]
It's a Rails autoloading thing; `docusign_controller.rb` needs to define `DocusignController` (with that exact capitalization): https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#project-structure

**Comment by kunalbotla** [comment]
oh I see, that clarifies it. thanks, @cjdenio!

I'm going to have this PR only make visual changes to the user and admin side of the dashboard

**Review by garyhtou — APPROVED** [review]
Thanks!

**Pull request merged**
