### PR TITLE
Fix Turbo(links) integration

### PR DESCRIPTION
**Pull request by cjdenio**
This PR fixes the currently-broken Turbolinks integration (breakage caused by [this line](https://github.com/hackclub/bank/blob/f6152871a15697dde7fc8b7bdd9b2991a4490c68/app/assets/javascripts/ui.js#L231)) and replaces it with [Turbo](https://github.com/hotwired/turbo), Turbolinks's successor.

also see https://github.com/reactjs/react-rails/issues/1103#issue-816722889

### CODE REVIEW

**Comment by maxwofford** [comment]
@cjdenio Excited for this! Just assign me as a reviewer once it's ready to check out

**Review by maxwofford — COMMENTED** [review]
I can't get past the signin step. Try it out on the preview deploy.

**Comment by cjdenio** [comment]
@maxwofford should be all set now (https://github.com/hotwired/turbo-rails/issues/12#issuecomment-754629885)

**Comment by maxwofford** [comment]
Screenrecording of me testing: https://youtu.be/e7_WBQwuLKI

**Comment by cjdenio** [comment]
Hmm, I'm pretty sure this is just Heroku's staging environment being oddly slow.

Turbo actually doesn't apply to certain pages with `<% include_modals %>` at the top; you'll notice [here](https://youtu.be/e7_WBQwuLKI?t=28) that the browser's just performing an ordinary page change.

Also, Turbo has its own cache that makes most route changes instantaneous; try switching between "Settings" and "Documentation" (also using the browser back/forward buttons) and it should be very fast.

**Review by maxwofford — APPROVED** [review]
Thanks for adding this! Let's go for it and see how it goes. Can you please rebase+merge? Please post in #bank-team once merged letting them know a large change in page loading has been merged and if they run into any issues of slower loading/links acting weird to post it immediately with you tagged.

**Comment by cjdenio** [comment]
Awesome! I'm not in #bank-team, so maybe you could merge + post?

**Pull request merged**
