### PR TITLE
Let there be 1Password

### PR DESCRIPTION
**Pull request by exu3**
This PR adds the events promo and admin card for 1Password.

Screen Shot 2022-04-24 at 00 21 57

Screen Shot 2022-04-24 at 00 21 52

The copy could probably use a pass.

### CODE REVIEW

**Comment by maxwofford** [comment]
Could we mention that Hack Club uses 1Password ourselves?

**Comment by maxwofford** [comment]
Forgot to mention, but really great job on the background- love how that looks in both themes.

**Comment by MelSmith104** [comment]
Looks great! Good to ship :)

**Comment by maxwofford** [comment]
And so there was 1Password, and it was good.

Orpheus 1:3

**Pull request merged**
