### PR TITLE
Add ability for event dashboard to show partner logos (e.g. MLH)

### PR DESCRIPTION
**Pull request by thesephist**
I didn't build the feature specifically for MLH, since my feeling is that this is something nice to have as we also onboard other event partners like HAX. Instead, each event gets an optional partner logo value:

Screen Shot 2019-09-01 at 02 28 35

And for MLH (currently the only partner using this), the logo is baked into the app as `mlh.svg`:

Screen Shot 2019-09-01 at 02 39 52
Screen Shot 2019-09-01 at 02 39 56

If we end up sticking with just MLH, I think we'll just make it a binary toggle on an event, which should be a really quick update.

We should run the look / appearance of the co-branding by MLH folks before we use it on any real events.

Should close #207

### CODE REVIEW

**Comment by lachlanjc** [comment]
Awesome, yeah. Though I think this header design has reached a breaking point & we should reconsider. This looks clunky & it’s confusing which of these are interactive & which are branding.

The simplest solution I can think of is make the header a (flex) container, then:

```
BANK MLH/HAX                      CHANGES DARK LOGOUT
```

So items are logically grouped. Thoughts?

**Comment by thesephist** [comment]
I like the new grouping idea. Worried it'll look weird because everything else in the UI is based on a sort of a center-aligned layout. Will play around with it.

**Comment by lachlanjc** [comment]
Only the event page is really designed that way, & could be adapted to a more left-aligned layout. Pages like Cards, Documents, etc are all left-aligned content in a centered container of dynamic width (width is based on the weight/hierarchy of the content—event page is widest, sub-content is medium, new/edit forms are small, etc), & this nav bar would inherit the width of the content container

**Review by tmb — APPROVED** [review]
Approving because we need to get this out rn. It's not absolutely the total best but can be improved down the road

**Pull request merged**
