### PR TITLE
[Reimbursements] Add an approve all expenses button

### PR DESCRIPTION
**Pull request by sampoder**
Fixes https://github.com/hackclub/hcb/issues/5632 in my opinion.

Adds this button (when no expenses have been approved):
 
Screenshot 2024-03-19 at 7 15 21 PM

Which does what you'd expect.

### CODE REVIEW

**Comment by garyhtou** [comment]
should it maybe be approve all & reimburse?

**Comment by sampoder** [comment]
I would them to still be separate stages, just so that its clear whats happening

**Comment by garyhtou** [comment]
i haven't thought much about this flow, but i just wanted to suggest it as another option

**Comment by sampoder** [comment]
Yeah, I'd like to get this in first, see how people feel about it. And if people would just prefer one button, switch over to that.

**Comment by garyhtou** [comment]
sounds good to me!

**Pull request merged**
