### PR TITLE
Add some basic styles to blockquotes in mailers

### PR DESCRIPTION
**Pull request by sampoder**
this will make the new donation messenger look much nicer:

Screenshot 2023-11-04 at 9 41 39 AM

### CODE REVIEW

**Comment by sarthaktexas** [comment]
lgtm :)

**Comment by garyhtou** [comment]
I love it! Would you mind adding a screenshot of what it looks like in gmail and outlook?

I like using [PutsMail](https://putsmail.com/) for testing that

**Comment by sampoder** [comment]
oh that screenshot is from Gmail, let me spin up Outlook

**Comment by sampoder** [comment]
here's Outlook @garyhtou:

Screenshot 2023-11-04 at 3 25 58 PM

**Review by garyhtou — APPROVED** [review]
Perfect! thanks :)

The reason I ask is because sometimes styles look great in gmail, but wonky in outlook

**Comment by sampoder** [comment]
All good, you bet!

**Pull request merged**
