### PR TITLE
Replace Airbridge with Airtable API using PAT

### PR DESCRIPTION
**Pull request by malted**
cc @maxwofford 

Airtable are revoking all legacy API keys in 2 days; and upon investigation I realised Airbridge is only used in one place.

Blocking on @maxwofford's #5055 to be able to use `Rails.application.credentials.airtable[:pat]`.

Closes https://github.com/hackclub/hcb/issues/5042

### CODE REVIEW

**Comment by malted** [comment]
Oh wait I should use the Airtable client

**Comment by garyhtou** [comment]
Yes! We've got https://github.com/sirupsen/airrecord installed; it's a Ruby client for Airtable

**Comment by garyhtou** [comment]
> Oh wait I should use the Airtable client

During my 1:1 with Malted, we decided to skip this for now. We'll continue using Faraday. If anyone like to take on switching Faraday to Airrecord, feel free to do so!

**Comment by garyhtou** [comment]
@maxwofford please update your PAT to allow access for:
- Onboard Verifications: `app4Bs8Tjwvk5qcD4`
- Bank Applications: `apppALh5FEOKkhjLR`

The admin cards for these are erroring due to insufficient permissions.

**Review by garyhtou — APPROVED** [review]
Code is good! We're just blocked by https://github.com/hackclub/hcb/pull/5127#issuecomment-1918438148

Let's merge by no later than Feb 1st, even if we don't have the PAT access updated

**Pull request merged**
