### PR TITLE
Vertically align items in ACH details toolbar

### PR DESCRIPTION
**Pull request by malted**
Alignment before:
image

Alignment after:
image

<details>
<summary>"alignment 🤓☝️":</summary>

</details>

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
great! FYI, i think this is an issue on other types of pages as well. any hcb code show page with a meatball menu likely has this issue

**Comment by sampoder** [comment]
Yeah we should check invoices and donations as well

**Comment by sampoder** [comment]
Donations and invoices seem good, same with cheques

**Comment by garyhtou** [comment]
okay, thanks!

**Pull request merged**
