### PR TITLE
Fix donation card header for long names

### PR DESCRIPTION
**Pull request by exu3**
Closes #2130

### CODE REVIEW

**Comment by garyhtou** [comment]
ooo cool!

we can also make this update for these (if they need them):
- app/views/hcb_codes/_partner_donation.html.erb
- app/views/hcb_codes/_check.html.erb
- app/views/hcb_codes/_stripe_card.html.erb
- app/views/hcb_codes/_disbursement.erb
- app/views/hcb_codes/_unknown.html.erb

**Comment by exu3** [comment]
> ooo cool!
> 
> we can also make this update for these (if they need them):
> 
> * app/views/hcb_codes/_partner_donation.html.erb
> * app/views/hcb_codes/_check.html.erb
> * app/views/hcb_codes/_stripe_card.html.erb
> * app/views/hcb_codes/_disbursement.erb
> * app/views/hcb_codes/_unknown.html.erb

Update _partner_donation.

I don't think _check and _disbursement  follow the same layout.

Will take a look at _stripe_card and _unknown.

Also slightly unrelated, but is there a reason why it's `_disbursement.erb` as opposed to `_disbursement.html.erb`?

**Comment by garyhtou** [comment]
> Also slightly unrelated, but is there a reason why it's `_disbursement.erb` as opposed to `_disbursement.html.erb`?

good catch! my bad 4000f9e2. could you please rename?

**Comment by exu3** [comment]
Should be all good, the other show pages don't seem to have the same issue as the invoices, donations, and ACH card headers.

**Review by garyhtou — APPROVED** [review]
perfect!

**Pull request merged**
