### PR TITLE
Birthday party mode

### PR DESCRIPTION
**Pull request by cjdenio**
Adds a little easter egg for birthday people.

Could possibly get annoying after a while– suggestions welcome.

https://user-images.githubusercontent.com/34525547/176224495-16e6562e-7fd7-4db6-888e-3ab5df5e3d85.mov

### CODE REVIEW

**Review by exu3 — COMMENTED** [review]
This is great!
- What if we also changed the favicon to :bank-hackclub-party:?
- I can get you a gif of bank-hackclub-party with better resolution. (sent via Slack)

**Review by maxwofford — APPROVED** [review]
Love the idea of a birthday mode, but could we switch it to something that's easier on the eyes?

**Comment by maxwofford** [comment]
Messaged in Slack, but my previous review is still an approval– let's merge now & tweak later.

**Review by exu3 — APPROVED** [review]

**Comment by cjdenio** [comment]
hang on to yer hats

**Pull request merged**
