### PR TITLE
Prepare to encrypt checks.description and comments.content

### PR DESCRIPTION
**Pull request by albertchae**
This should be the final set of columns for https://github.com/hackclub/bank/issues/2541
It turns out checks.memo is used for search, so we are omitting that
from encryption.

After this PR is merged, need to run this on prod console
```
Lockbox.migrate(Check)
Lockbox.migrate(Comment)
```

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Wahoo! Getting close.

I just re-reviewed the fields & it looks like I misspoke before– the `transaction_memo` field is generated by us for checks & we don't need to encrypt it.

**Comment by albertchae** [comment]
@maxwofford sounds good, I removed that column from this PR

**Comment by maxwofford** [comment]
Awesome, go for merge once you're ready!

**Comment by albertchae** [comment]
Finished running this on prod

```
Lockbox.migrate(Check)
Lockbox.migrate(Comment)
```

**Pull request merged**
