### PR TITLE
Improve markdown notice on comments

### PR DESCRIPTION
**Pull request by maxwofford**
Before 
Screenshot 2019-06-01 14 56 52

After
Screenshot 2019-06-01 15 03 09

### CODE REVIEW

**Review by tmb — APPROVED** [review]
LGTM

**Comment by zachlatta** [comment]
This looks freakin' awesome.

**Comment by maxwofford** [comment]
Haven't heard anything from @lachlanjc, so going ahead with merging

**Comment by lachlanjc** [comment]
Ah, sorry this slipped by @MaxWofford. Looks great. My two things:

- Would be nice to use the Hack Club Icons for the Markdown icon, this sticks out
- Just check that this works elegantly on a small screen (iPhone SE?) with a long name. Haven’t checked the code but make sure things wrap nicely

**Pull request merged**
