### PR TITLE
Make WebAuthn auth flow even smoother

### PR DESCRIPTION
**Pull request by cjdenio**
👋 It's me again, back with more WebAuthn-y stuff.

This PR reworks the auth flow to remove the `/users/webauthn` page, thus making sign-ins even quicker.

###### Kunal giving feedback on the current flow

Screen Shot 2022-04-16 at 9 45 57 PM

###### No More "Authenticate"!

Screen Shot 2022-04-16 at 9 41 39 PM

### CODE REVIEW

**Comment by sampoder** [comment]
That's sick!

**Comment by maxwofford** [comment]
Whoops! that was a misclick, sorry!

**Review by garyhtou — APPROVED** [review]
veryy cool!

**Comment by kunalbotla** [comment]
yay; this is awesome!

**Comment by maxwofford** [comment]
Not sure if this is part of this update, but I tried signing in today in FF which doesn't support device auth. Normally I can just go straight to "Get a login code", but a popup/warning blocked me from clicking when it first loaded in.

Screen Shot 2022-04-19 at 11 58 01

**Comment by maxwofford** [comment]
Got through this step fine by just clicking cancel, but was confused.

**Comment by maxwofford** [comment]
That's nice! I think that's a quick incremental improvement that makes it much less confusing.

**Pull request merged**
