### PR TITLE
Upgrade Ruby from 2.7.3 to 2.7.5

### PR DESCRIPTION
**Pull request by albertchae**
- https://github.com/ruby/ruby/compare/v2_7_3...v2_7_5
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/

We're doing this to resolve a nokogiri/glibc issue in our docker setup
https://github.com/hackclub/bank/issues/2437

From @garyhtou in that thread:

It became an issue when the gem version was bumped in https://github.com/hackclub/bank/pull/2334

The native precompiled gem added in https://github.com/sparklemotion/nokogiri/pull/2332
requires glibc >= 2.29, however, our Docker ruby base image is running 2.28

### CODE REVIEW

**Comment by albertchae** [comment]
ok looks like I forgot to bump the ruby version for these CI steps, I'll come back to this later

**Comment by albertchae** [comment]
Just got this email from heroku, is this common on PR deployments?

image

**Comment by maxwofford** [comment]
@albertchae Yep! you can safely ignore these– you'll get them on every preview deploy

**Review by maxwofford — APPROVED** [review]
This looks good to merge. Just tested it on my m1 macbook air & it works too, so it seems like this fixes #2437 just fine.
Screen Shot 2022-04-07 at 22 31 44

**Comment by maxwofford** [comment]
Looks great! Go ahead and merge once you're ready.

**Comment by albertchae** [comment]
@maxwofford great thanks, merged!

**Pull request merged**
