### PR TITLE
Fix invalid environments definition for branch deployment workflow

### PR DESCRIPTION
**Pull request by northeastprince**
Take 2 folks, sorry @maxwofford 😅

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Np! Hope it works this time.

**Comment by northeastprince** [comment]
.deploy noop

**Comment by northeastprince** [comment]
Yes...?!

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
due to testing on a closed PR, this is expected - running it again, fingers crossed

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
"worked"! not really, forgot to add the SSH used by this to the new "atm" (dev) servers

**Comment by northeastprince** [comment]
take 300:

**Comment by northeastprince** [comment]
.deploy atm1

**Comment by northeastprince** [comment]
Cool, just need to fix the SSH hostkey mismatch - but this is working!!! @maxwofford @garyhtou #3574

**Pull request merged**
