### PR TITLE
Add papertrail to Column::AccountNumber

### PR DESCRIPTION
**Pull request by devramsean0**
## Summary of the problem
We should probably be tracking changes to financial models, and according to Gary in #5065 We aren't tracking them for the column::AccountNumber model

## Describe your changes
Added `has_papertrail` to the associated model

### CODE REVIEW

**Review by cjdenio — APPROVED** [review]

**Comment by sarthaktexas** [comment]
lgtm!

**Review by garyhtou — APPROVED** [review]
¡Great!

**Comment by devramsean0** [comment]
Can i merge?

**Comment by garyhtou** [comment]
@sarthaktexas should be able to merge once:
1. There is an approval from a mentor
2. AND there is an approval from myself or Caleb

I do ask that the mentors make the merge since they're able to monitor our APM (Application Performance Monitoring) tools immediately after merge to make sure there are no new errors from the PR

**Pull request merged**
