### PR TITLE
Fix attach_receipt page title & anonymous user_mention

### PR DESCRIPTION
**Pull request by exu3**
attach_receipt page title:

<table>
<tr>
	<td>Previously</td>
	<td>
Now

</td>
</tr>
<tr>
	<td>
Screen Shot 2022-04-15 at 10 45 28
</td>
	<td>
Screen Shot 2022-04-15 at 11 11 51
</td>
</tr>
</table>

Anonymous user mention (related to #2436)

<table>
<tr>
	<td>Previously</td>
	<td>Now</td>
</tr>

<tr>
	<td>
Screen Shot 2022-04-15 at 12 09 55

</td>

<td>
Screen Shot 2022-04-15 at 11 02 36
</td>
</tr>
</table>

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
good work!!!!!

thought: what if we made the profile pic a random pic from [hackclub/draw-a-dino](https://github.com/hackclub/dinosaurs)

**Comment by exu3** [comment]
Cool idea! https://geta.dino.icu/dino.png

**Comment by exu3** [comment]
geta.dino.icu doesn't currently have reliable hosting (working on it though), so I'm going to merge without that change for now.

**Comment by garyhtou** [comment]
it honest looks like something that we can next.js-ify (convert from express/node) and throw on vercel

**Pull request merged**
