### PR TITLE
Fix Script Names in Readme

### PR DESCRIPTION
**Pull request by jaspermayone**
## Summary of the problem

During my open source onboarding with @garyhtou we caught that the name of the scripts were wrong, so I have fixed said script names.

## Describe your changes

Edited the script names.

### CODE REVIEW

**Review by garyhtou — CHANGES_REQUESTED** [review]
Thanks! Can you also update line 46?

**Comment by jaspermayone** [comment]
Yep! On it!

**Review by garyhtou — APPROVED** [review]
Great!

**Comment by garyhtou** [comment]
congrats on your first PR!

**Comment by jaspermayone** [comment]
Thanks!

**Pull request merged**
