### PR TITLE
[UI] Financials: Add raised/spent metrics

### PR DESCRIPTION
**Pull request by lachlanjc**
## Summary of the problem

Right now, it's hard to get a sense (esp in Transparency Mode) of the total budget of an org, since it only shows ending balance. Adding raised/spent metrics adds some more insight into an org's budget.

## Describe your changes

CleanShot 2024-08-29 at 17 47 34@2x

Issue that should be solved separately: these metrics don't include fees, so the numbers are off! This is an existing issue I didn't touch.

### CODE REVIEW

**Comment by sampoder** [comment]
There's a fair bit of crossover between this PR & https://github.com/hackclub/hcb/pull/7105

**Comment by lachlanjc** [comment]
@sampoder Oh awesome! I'm not able to see what that PR looks like since I don't have access to Manu's repo & it's not a branch in ours. I think better overview widgets are absolutely the place to invest, but that new page is a much larger project, and I'd advocate we start small with this design then integrate it into a more expansive Overview!

**Comment by garyhtou** [comment]
Regarding https://github.com/hackclub/hcb/pull/7105, @dwahbe and I discussed looping in @lachlanjc shortly.

Since we've decided to move toward https://github.com/hackclub/hcb/pull/7105 and the PR is almost here, I ask that we finish that up. Since I'll be OOO, @manuthecoder / @sampoder, once the remaining few data and CSS bugs are cleaned up, please work with @dwahbe and @lachlanjc to polish it up and release it.

**Comment by dwahbe** [comment]
Love this! We will take widgets and put them in home page.

**Pull request closed without merging**
