### PR TITLE
Card freezing

### PR DESCRIPTION
**Pull request by maxwofford**
Screen Shot 2020-11-23 at 1 28 11 PM
Screen Shot 2020-11-23 at 1 27 52 PM

Basic implementation of card freezing and defrosting. Freezing/defrosting is instant & will be reflected on Stripe immediately.

### CODE REVIEW

**Comment by maxwofford** [comment]
Spending money on a frozen card declines TXs

Screen Shot 2020-11-23 at 1 36 43 PM

**Comment by lachlanjc** [comment]
FYI there's a snowflake icon on https://icons.hackclub.com/!

**Comment by maxwofford** [comment]
Screen Shot 2020-11-23 at 2 15 19 PM


"Freeze" button now has "freeze" icon

**Comment by maxwofford** [comment]
Now there's a distinct difference between "frozen" (temporary holds) and "canceled" (permanent holds) https://www.youtube.com/watch?v=JGEE7pqyBsU

**Comment by maxwofford** [comment]
There is some tweaking to do on the emails sent (ie. rejected TX on a frozen card should probably email you w/ a link to unfreeze your card), but I'm going to merge what I have here & get a feel for it in production before making those copy changes.

**Comment by maxwofford** [comment]
For the sake of documentation, this is what the declined TX email looks like if your card is frozen:

Screen Shot 2020-11-23 at 5 21 31 PM

**Pull request merged**
