### PR TITLE
(fix) airtable id error no longer occurs when making event

### PR DESCRIPTION
**Pull request by tmb**

### CODE REVIEW

**Comment by thesephist** [comment]
Gonna approve since it fixes the issue + it's a pretty annoying issue. But curious if @lachlanjc has any idea what might be going on here. Apparently mutating `event_params` itself doesn't do what we might expect it to, and I'm not deep enough into ruby/rails to know what might be going on here.

**Review by thesephist — APPROVED** [review]
:shrug:

**Comment by lachlanjc** [comment]
Lol @ this solution @tmb though it makes sense. Yeah, now that I think of it you’re not allowed to alter params for security/networking/something-I-don’t-know-much-about Rails reasons, & that‘s logical. This solution is perhaps the hackiest possible. A few better ones:

- Add a before save callback/hook on the Event model to set this
- Can this value just be a default in the database with a migration? Idk
- Use a merge/reverse_merge when creating/updating the Event with event_params

**Comment by thesephist** [comment]
Hmmmm before save callback makes sense. If that's a quick solution, that's probably a cleaner way to do this.

If I'm understanding the suggestion correctly, the reason it can't be a blank default value is b/c the airtable id is also an indexed column, so it has to be unique and `''` is not unique for multiple events.

**Comment by lachlanjc** [comment]
Even simpler, couldn’t you put the merge directly on the event_params method? https://github.com/asm-helpful/helpful-web/blob/master/app/controllers/users_controller.rb#L36

**Comment by tmb** [comment]
there are probably better ways to fix this as listed above, but i think that this fixes the issue & is easy to read, plus this is kinda important to get patched

**Pull request merged**
