### PR TITLE
Add StickerNinja Discount perk card

### PR DESCRIPTION
**Pull request by rluodev**
## Describe your changes
Adds stickerninja perk card for new perk

Logged-in view (it's a click to copy field)

Screenshot 2024-04-12 at 9 26 38 PM

Logged-out view

Screenshot 2024-04-12 at 9 27 04 PM

### CODE REVIEW

**Comment by hackliv** [comment]
🎉🎉🎉🎉 the ninjas look rly cool

**Comment by hackliv** [comment]
Can you send me the memo - I have some suggested phrasing edits!

**Comment by rluodev** [comment]
> Can you send me the memo - I have some suggested phrasing edits!

Sure!

**Comment by hackliv** [comment]
I might also suggest adding "Promo Code" somewhere above the promo code to make it clear. 

Also can we hide the second part "Please don't share this discount code publicly, as it is exclusively for the use of HCB's fiscally sponsored organizations." in Logged-out view so that it doesn't tempt people to just join to get that code!

**Comment by rluodev** [comment]
Yep it’s hidden already for logged-out ppl

**Comment by hackliv** [comment]
perfect thanks, just wanted to make sure that was still true for updated memo!

**Comment by sampoder** [comment]
The ninjas are so cool

**Comment by garyhtou** [comment]
After @hackliv's approval, can either @sarthaktexas / @sampoder approve for engineering please?

Good to merge after their approvals

**Comment by garyhtou** [comment]
🥷

**Comment by hackliv** [comment]
Hey guys, lets continue to make sure we have comms in place first before merging live!

@Soar1826 do you want to draft a Slack announcement and Changelog post?

**Comment by rluodev** [comment]
sure!

**Review by hackliv — APPROVED** [review]

**Review by sampoder — CHANGES_REQUESTED** [review]
Can we remove the unrelated (formatting?) changes?

**Comment by rluodev** [comment]
P sure the css file changes were linted

**Comment by sampoder** [comment]
Yeah, can we remove them or move them into a separate PR? Some of them look
off.

**Comment by rluodev** [comment]
fixed!

**Comment by rluodev** [comment]
@sampoder can we get this reviewed + merged today? would like to launch perk asap

**Review by sampoder — APPROVED** [review]

**Comment by sampoder** [comment]
In future: re-request a review from me when you need it, I get a lot of GitHub notifications!

**Pull request merged**
