### PR TITLE
3389 update poppler buildpack new review app

### PR DESCRIPTION
**Pull request by albertchae**
Same as https://github.com/hackclub/bank/pull/3395 but this is just to deploy a new review app, since I don't have permissions yet to deploy them manually

- Fix pdf to image preview conversion by upgrading poppler library
- Use hackclub's buildpack

test url:
https://bank-hackclu-3389-updat-s0dxqy.herokuapp.com/the-innovation-circuit/documents

### CODE REVIEW

**Comment by garyhtou** [comment]
i think you might have permission here, but lmk if this isn't the case
https://dashboard.heroku.com/pipelines/e61db6c3-496d-4233-ad3c-4a29752dcc12

**Comment by albertchae** [comment]
@garyhtou is this what I'm supposed to see https://devcenter.heroku.com/articles/github-integration-review-apps#manual-creation? Because I only see this give feedback button 
image

**Comment by garyhtou** [comment]
I've bumped your perms up to admin for the entire Hack Club team, lmk if that works for you now
image

**Comment by albertchae** [comment]
@garyhtou thanks! looks like those permissions work. Closing this PR in favor of the original now that I can make review apps based on it https://github.com/hackclub/bank/pull/3395

**Pull request closed without merging**
