### PR TITLE
[Reimbursements] Add Papertrail to Expenses & display approved by / approval removed by

### PR DESCRIPTION
**Pull request by sampoder**
Screenshot 2024-03-16 at 9 31 21 AM
Screenshot 2024-03-16 at 9 31 31 AM

Closes https://github.com/hackclub/hcb/issues/5582

### CODE REVIEW

**Comment by garyhtou** [comment]
Can we also add paper trail to report? and make sure everything works correctly when deleting

**Comment by sampoder** [comment]
Papertrail is already in the report, it's being used to generate the conversation. Wdym by deleting?

**Review by sarthaktexas — APPROVED** [review]

**Comment by garyhtou** [comment]
Sometimes validations fail unexpectedly when working with deleted records.

For example, a unique constraint might validate with all records, and not just the non-deleted records.

I'd suggest looking through our validations to see if any are affected

**Comment by garyhtou** [comment]
Oh my bad, I just realized i was thinking of `acts_as_paranoid` instead of `has_paper_trail`

**Pull request merged**
