### PR TITLE
[Gemfile] Specify Ruby version using `file` argument

### PR DESCRIPTION
**Pull request by garyhtou**
Bundler 2.4.19 [introduced](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2419-august-17-2023) a new `file` param to make it easier/cleaner to specify a Ruby version using a file (e.g. `.ruby-version` or `.tool-versions`)

### CODE REVIEW

**Review by albertchae — DISMISSED** [review]
I've made this change in other repos, LGTM as long as people aren't using rvm

**Comment by garyhtou** [comment]
thanks for reviewing! does this change cause issues for rvm?

**Comment by cjdenio** [comment]
I'd run a staging deploy first to make sure [Heroku understands the file: argument](https://devcenter.heroku.com/articles/ruby-versions)

**Comment by garyhtou** [comment]
we're good!
image

_the build later failed bc it was missing the proper buildpacks. but since it detected the right ruby version (and I'm lazy), I feel confident that I'll work_

**Comment by garyhtou** [comment]
>_the build later failed bc it was missing the proper buildpacks. but since it detected the right ruby version (and I'm lazy), I feel confident that I'll work_

update: was too confident... build failed 🤦‍♂️

https://github.com/hackclub/hcb/pull/6158

**Pull request merged**
