### PR TITLE
Documents: add the upload date

### PR DESCRIPTION
**Pull request by sampoder**
## Summary of the problem

Sarthak wants it, closes https://github.com/hackclub/hcb/issues/5271.

## Describe your changes

"Just put the date." - @sarthaktexas

Screenshot 2024-02-22 at 4 31 03 PM

### CODE REVIEW

**Comment by cjdenio** [comment]
Hmm, is this useful for users? Seeing "2020" and "Linus L" ~~who's that~~ might be confusing

**Comment by sampoder** [comment]
I'm not sure, @sarthaktexas what was your thinking when you asked for it?

**Comment by garyhtou** [comment]
> Hmm, is this useful for users? Seeing "2020" and "Linus L" ~who's that~ might be confusing

In prod, all the common documents uploaded by past HCB team members have been switched to the HCB user

image

**Comment by sarthaktexas** [comment]
was thinking this could be for org specific docs. common documents don't need a date -- also @garyhtou thoughts on changing common docs author to be hcb? we can still have the actual person on the common docs upload page and/or on the full page document page (the one w edit, destroy, etc.) 

@cjdenio this is for when orgs have multiple fscs. currently ops names them "feb 2024 fiscal..." does that help you understand my stance on this?

**Comment by garyhtou** [comment]
> also @garyhtou thoughts on changing common docs author to be hcb? we can still have the actual person on the common docs upload page and/or on the full page document page (the one w edit, destroy, etc.)

Cool, let's either make it HCB or remove it entirely for common docs (for the user views)

**Comment by sampoder** [comment]
Alrighty! What I've done is hidden the user and date for common docs

**Pull request merged**
