### PR TITLE
Try removing node_modules after asset compile to reduce slug size

### PR DESCRIPTION
**Pull request by albertchae**
https://github.com/hackclub/bank/issues/3410

From this blog post https://blog.saeloun.com/2020/05/04/how-to-reduce-heroku-slug-size.html

Goes from
`Warning: Your slug size (494 MB) exceeds our soft limit (300 MB) which may affect boot time.`
to
`Warning: Your slug size (486 MB) exceeds our soft limit (300 MB) which may affect boot time.`

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
ty!

**Comment by albertchae** [comment]
Prod deploy went from
` !     Warning: Your slug size (499 MB) exceeds our soft limit (300 MB) which may affect boot time.`
to this
`!     Warning: Your slug size (492 MB) exceeds our soft limit (300 MB) which may affect boot time.`

so this change bought us some room 🤏

**Comment by albertchae** [comment]
I'm seeing this error which I don't understand, so I'm going to revert for now. https://github.com/hackclub/bank/actions/runs/3961405358

**Comment by garyhtou** [comment]
> I'm seeing this error which I don't understand, so I'm going to revert for now. [hackclub/bank/actions/runs/3961405358](https://github.com/hackclub/bank/actions/runs/3961405358)

Yeah I'm not understanding it either. However, it seems to be limited to GitHub Pages deployment.

GitHub pages serves our heroku application error page (set by ERROR_PAGE_URL env var)
https://github.com/hackclub/bank/tree/main/docs

**Comment by albertchae** [comment]
@garyhtou yeah what's normally on the https://hackclub.github.io/bank/ page? I'm not even sure

**Comment by albertchae** [comment]
Looks like it failed anyway with the revert https://github.com/hackclub/bank/actions/runs/3961626667/jobs/6787291362

**Comment by garyhtou** [comment]
https://www.githubstatus.com/
image

**Comment by albertchae** [comment]
@garyhtou ah right, I saw a warning on heroku and didn't click through. Thanks for the heads up. I'm going to revert the revert

**Comment by garyhtou** [comment]
sounds good! I think the PR is fine, it just github pages that's having issues

**Pull request merged**
