### PR TITLE
Add Apple Pay support for donations

### PR DESCRIPTION
**Pull request by cjdenio**
This PR lets people donate with apples! Er... Apple Pay. (i like apples better though)
Screen Shot 2022-06-04 at 4 39 56 PM
Screen Shot 2022-06-04 at 4 36 20 PM
Screen Shot 2022-06-04 at 4 36 12 PM

Closes #2498

### CODE REVIEW

**Comment by cjdenio** [comment]
(Note: Apple Pay won't work in staging because the domain isn't [verified](https://stripe.com/docs/stripe-js/elements/payment-request-button?html-or-react=html#verifying-your-domain-with-apple-pay))

**Comment by maxwofford** [comment]
Because this could impact production donations, could you drop this into a new file (ie. `final_donation_apple_pay.html.erb`) and render it conditionally (ie. `?apple=true` or `user.admin?`)? I'd love to test this in production if the staging environment isn't working.

**Comment by cjdenio** [comment]
Oh, to be clear: donations still work in staging. Stripe just doesn't show the Apple Pay option until your domain is verified.

**Review by maxwofford — APPROVED** [review]
https://github.com/hackclub/bank/pull/2630#issuecomment-1147635629

Awesome! I just tested in staging & it looks good. Go for merge!

**Pull request merged**
