### PR TITLE
Admin Side Country Codes

### PR DESCRIPTION
**Pull request by kunalbotla**

### CODE REVIEW

**Comment by kunalbotla** [comment]
it works!

image

**Comment by kunalbotla** [comment]
@MelSmith104 @maxwofford I think this is ready to merge

**Comment by kunalbotla** [comment]
You can test this by editing an existing event to give it a country code or by creating a new event with the country code dropdown

**Comment by maxwofford** [comment]
this is dope! @MelSmith104 grab me and we can review together

**Comment by MelSmith104** [comment]
Just checked out - looks awesome! Did both editing an existing org and created new org and both worked perfectly. Yes please merge! In the future - I'd love to have full name of country, extra feature that can happen later :)

**Pull request merged**
