### PR TITLE
Fixes Double Donations 

### PR DESCRIPTION
**Pull request by clarencejychan**
Fixes #1905 

Tested by running `PendingEventMappingEngine::Settle::Donation.new.run` on rails console

Thanks to @garyhtou  for helping to explain HCB codes

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
No problem! glad to help! :smile:

**Review by maxwofford — COMMENTED** [review]
This looks great! Could you remove the unrelated change on events_controller & rebase? I'm going to run it locally right now.

**Review by maxwofford — APPROVED** [review]
It worked locally, go for rebase+merge!

**Comment by maxwofford** [comment]
While this solves the syncing issue, there's a UX problem here to:
Screen Shot 2021-11-03 at 09 44 26
Screen Shot 2021-11-03 at 09 44 37

As a user, I expected my donor to send $100, and the donation page said they did. Is the missing amount a fee? Why it is not there?

Let's fix that in a separate issue.

**Pull request merged**
