### PR TITLE
Add API route for admin task size

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
@lachlanjc try this out! log into the review app & go to https://bank-hackclu-js-admin-t-wlabsg.herokuapp.com/admin_task_size?task_name=negative_events

**Comment by lachlanjc** [comment]
I waited 30+ seconds for login after submitting the code & got an application error before getting to the homepage :( @maxwofford

**Comment by maxwofford** [comment]
@lachlanjc can you record that? I’m not experiencing that from the review app on my phone. Make sure to login as an admin— this is still a wip and I haven’t played with permissions yet

**Comment by maxwofford** [comment]
Not pretty, but here's the new experience loading the admin task page (previously took ~20s to first render):

https://www.youtube.com/watch?v=97klUPrKfxc

**Comment by iamcpdev** [comment]
Omg yessss

**Comment by maxwofford** [comment]
I'm going to merge this to show it off at the morning meeting

**Pull request merged**
