### PR TITLE
[AchTransfer] Encrypt Routing Number Part 1/3

### PR DESCRIPTION
**Pull request by rluodev**
This is part 1 of 3.

In this step, we add a `:routing_number_ciphertext` field to the `:ach_transfers` table and mark the field as migrating for lockbox.

Before step 2, someone with prod access will need to run `Lockbox.migrate(AchTransfer)` to add unencrypted values to the ciphertext field. They'll also need to run `BlindIndex.backfill(AchTransfer)` to add blind index values.

Step 2 will consist of ignoring the `:routing_number` field in ruby and papertrail.

Step 3 will consist of dropping the `:routing_number` column from the DB.

### CODE REVIEW

**Comment by sampoder** [comment]
Can we make it searchable? https://github.com/ankane/blind_index

**Comment by rluodev** [comment]
Wait but routing numbers are all the same cause they’re from the same bank tho

**Comment by rluodev** [comment]
If you searched a routing number it’d just return all the ach transfers

**Comment by sampoder** [comment]
Hmm fair enough, maybe we can do that separately if we ever add it to account number

**Comment by sampoder** [comment]
I just generally find having blind indexes helpful but if you think it's too much of a hassle, I'm chill with going without it

**Comment by rluodev** [comment]
Oh wait no actually that’s a brain fart on my end; I’ll add blind index

**Comment by rluodev** [comment]
(I ended up confusing ach transfer and the account numbers we have for each org)

**Review by sampoder — APPROVED** [review]

**Pull request merged**
