### PR TITLE
Add preview for docx files

### PR DESCRIPTION
**Pull request by Ved235**

### CODE REVIEW

**Comment by Ved235** [comment]
closes #7733

**Comment by sampoder** [comment]
Hey, I tried this in staging and it doesn't seem to be working:

Screenshot 2024-09-01 at 10 07 20 AM

I've tried adding `libreoffice` to our `Aptfile` to fix that.

**Comment by Ved235** [comment]
Could we talk in slack about this, writing comments here seems kinda slow!

**Comment by sampoder** [comment]
Heroku is refusing to deploy this now that we're installing `libreoffice` (our Heroku doesn't use Docker to deploy):

```
 !     Compiled slug size: 897.8M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```

I think we're going to have to find another way or skip out on doing this sadly.

**Comment by Ved235** [comment]
Ok, I am going to try to look for another way.

**Comment by sampoder** [comment]
Yeah fs! Sounds good

**Pull request closed without merging**
