### PR TITLE
Create `HcbCode#pinnable?` and use it hide the pin option

### PR DESCRIPTION
**Pull request by sampoder**
Cleaner solution to what we had before.

### CODE REVIEW

**Review by garyhtou — COMMENTED** [review]
what if we moved the condition into the partial?

**Comment by garyhtou** [comment]
hahah the typo was my fault lolimage

**Comment by garyhtou** [comment]
can you get rid of this method?
https://github.com/hackclub/bank/blob/b3619501bdd10134d7b0ce9d57317e55e6dc3450/app/models/hcb_code.rb#L353

**Comment by sampoder** [comment]
I've instead gone with `pinnable?` and also integrate a check for `event` (this error happened last night)

**Review by garyhtou — APPROVED** [review]
makes sense to me

**Pull request merged**
