### PR TITLE
Only run Github Actions on `pull_request` & pushes to `main`

### PR DESCRIPTION
**Pull request by sampoder**
## Summary of the problem

We're running into all sorts of funky Github actions: https://github.com/hackclub/hcb/issues/4717

## Describe your changes

If we merged this, we'd only run jobs on the `pull_request` event. Thoughts?

### CODE REVIEW

**Comment by northeastprince** [comment]
I would just run CI on push but not pushes to main.

**Comment by sampoder** [comment]
That would recreate the original issue, we need the `pull_request` event so that we can run CI on private forks

**Comment by garyhtou** [comment]
What are your thoughts on keeping `pull_request` and `push`, but filtering pushes to only the `main` branch? I'd assume this would allow us to run checks on pull requests and the main branch.

Running checks on the `main` branch isn't completely necessary, but is nice in case there is a (rare) commit directly to `main`

**Comment by sampoder** [comment]
I like that idea!

**Comment by northeastprince** [comment]
The issue was caused by CI bring run on push and PR events, which is redundant with the former, so we should be fine just having CI run on push events.

**Comment by sampoder** [comment]
CI does not run on push events from private forks, hence we need the pull_request event.

**Review by garyhtou — APPROVED** [review]

**Pull request merged**
