### PR TITLE
Don't require receipts on 0 USD TXs

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
Closes #934

**Comment by maxwofford** [comment]
@lachlanjc just want to confirm, have you been using this scope for everything receipt related?

**Comment by maxwofford** [comment]
Also added for Emburse TXs

**Comment by lachlanjc** [comment]
Yup! Thanks!

**Comment by maxwofford** [comment]
before:
Screen Shot 2020-10-09 at 1 16 53 PM

after:
Screen Shot 2020-10-09 at 1 21 29 PM

**Pull request merged**
