### PR TITLE
Bump Ruby version to 3.2.4

### PR DESCRIPTION
**Pull request by garyhtou**
there's an issue with docker that I haven't been able to figure out!

### CODE REVIEW

**Comment by garyhtou** [comment]
If anyone has some time, feel free to debug this

**Comment by cjdenio** [comment]
@garyhtou can you share the specific issue you're running into?

**Comment by cjdenio** [comment]
```
docker volume rm bank_node_modules bank_tmp bank_gems

docker build web --no-cache
```

might fix it if it's the same issue I ran into

**Comment by garyhtou** [comment]
ah interesting, okay!

**Comment by garyhtou** [comment]
@rluodev would you mind testing this? I remember you ran into the same issue

**Comment by garyhtou** [comment]
In the meantime, @cjdenio can you sanity check this pr and merge so that we can get the security patches in prod?

**Review by cjdenio — APPROVED** [review]

**Pull request merged**
