### PR TITLE
[Impersonate] Add power user ability to impersonate a user

### PR DESCRIPTION
**Pull request by motdotla**
Useful for debugging issues around gsuite and for other uses.

How to use:

While signed in as an admin only, you can type in the following url:

```
http://bankurl/users/impersonate?user_id=1234
```

You will then be logged in as that user. The feature is a little janky in that then you will have to log back out to log back in as an admin. That can be solved later but requires much more complexity via multiple cookies typically.

Here's a gif demonstrating its usage and verifying it is only permitted as an admin.

### CODE REVIEW

**Review by iamcpdev — DISMISSED** [review]
lgtm

**Comment by maxwofford** [comment]
Love this feature @motdotla! Can we also add a link for this on the admin search page under each user's account? (https://bank-hackclu-impersonat-ibnqlu.herokuapp.com/admin_search)

**Comment by iamcpdev** [comment]
I can add this super quick. Give me a sec

**Review by lachlanjc — DISMISSED** [review]

**Comment by iamcpdev** [comment]
Lol I fell asleep 😂. I'll add this later today.

**Comment by iamcpdev** [comment]
Hey @motdotla I though I was going to be able to play around with this but I can't figure out rails path helper.

I'll leave this for you whenever you get to it.

**Review by iamcpdev — COMMENTED** [review]
Looks great

**Comment by iamcpdev** [comment]
I had to revert this @motdotla because it gives this after signing into bank.hackclub.com

image

Slack me if you have any other questions

**Pull request merged**
