### PR TITLE
Add quick actions to org Financials

### PR DESCRIPTION
**Pull request by lachlanjc**
## Summary of the problem

Our navbar has become a bit overgrown with actions users don't need access to from everywhere across HCB—specifically, the Check Deposit & Account Numbers pages. The use case for these is rarely in the middle of a journey on HCB; typically you're coming to HCB to deposit the check or grab the account numbers, so we can put them right with the rest of your bank account info & tools on the Financials page, and clean up the sidebar.

## Describe your changes

I've redesigned Account Numbers as one modal, and integrated the other actions I think people want to take most frequently right on the Financials page.

https://github.com/user-attachments/assets/91cba850-bc3b-487a-82b6-1fcadd5ff588

### CODE REVIEW

**Comment by sampoder** [comment]
Umm... so... I already built this out as part of https://github.com/hackclub/hcb/pull/7105. Glad to hear we're thinking similar things! But yeah fyi, our implementations are near identical

**Comment by lachlanjc** [comment]
Oh! I'm still not able to access that branch. I built this out last May as part of a design refresh but just got it into its own PR.

**Comment by sampoder** [comment]
@manuthecoder would you be able to give Lachlan access to your fork? Sorry I'm not sure what's the best way to give them access

**Comment by sampoder** [comment]
I'm going to close this in favour of https://github.com/hackclub/hcb/pull/7105, thanks for putting this together though I'll use them as inspiration when reviewing #7105!

**Comment by lachlanjc** [comment]
Hey @sampoder! I believe in open & honest professional feedback, so wanted to tell you this bluntly so you don't have to read between the lines. Happy to chat anytime more about it, but it comes from a good place.

I've learned some incredible things from times when I opened a PR at work and had someone pop in with feedback of the shape "I don't think this is the right solution to this problem, how about we consider Y instead?" or "I'm concerned about a trade-off this PR makes, here's a way we could make different trade-offs." But I have never in my professional career closed someone's PR or had one of my PRs closed without talking to the author about it; it's not done. Using a PR a paid coworker spent a day building as "inspiration" comes across poorly, but more importantly, it's a wasteful use of the org budget, it duplicates work, and robs our customers of improvements we've already spent the time and money to build. I am super down for critical feedback---I want you to look through my work with a fine-tooth comb & raise trade-offs that could have negative consequences or ways to improve the clarity & functionality of designs. But as a primary steward of the codebase, when you're paying people to push forward specific product priorities, you owe code review & feedback on their PRs.

In this case, I got this design approved with product owners in May. I'm totally happy if we want to move these buttons to a new page when we finish making another page. In the meantime, this PR is ready to launch, and is a big win for customers we can announce now. When we make a new homepage, awesome, we can decide if the controls should move. PRs should be reviewed through the lens of whether 1) this is a win for customers in alignment with our direction and 2) if there's consequences for code maintenance/ops burden that mean we need to alter/delay. Keeping PRs scoped reduces risk everywhere, and making sure we're happy with the implementation of this feature in this PR helps us move faster with the new homepage design.

Hope I'm not putting you on blast here, but I want you to know that expectation on eng teams for the future, and excited to help ship some wins together!

**Comment by sampoder** [comment]
Hey Lachlan, sorry that this happened. I think there's been a bit of a miscommunication. We've already implemented in the other PR, which I've been asked to make my priority and have been working with Manu on for months.

I appreciate you making this PR but I wasn't involved in it beforehand and have no context behind it.

I'm am currently treating Bank like an open-source project when reviewing PRs from outside of the core engineering team. In the future, please make issues before making PRs. That gives us a chance to bring up things like this already having been built. Without that prior notice, there will unfortunately be times when a PR isn't in line with the work that the rest of the team is doing and in those cases, they'll be closed.

I hope you understand where I'm coming from. All I ask is that going forward, issues are made so we prevent duplicate work.

**Pull request closed without merging**
