### PR TITLE
Remove selenium/webdriver related gems as well as the heroku buildpacks

### PR DESCRIPTION
**Pull request by albertchae**

### CODE REVIEW

**Comment by albertchae** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3695** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3695" target="_blank">Graphite</a> 
    * **PR #3741** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3741" target="_blank">Graphite</a> 
      * **PR #3742** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3742" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/hackclub/bank/3742?utm_source=stack-comment).

**Comment by albertchae** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3695** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3695" target="_blank">Graphite</a> 
    * **PR #3741** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3741" target="_blank">Graphite</a> 
      * **PR #3742** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3742" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/hackclub/bank/3742?utm_source=stack-comment).

**Review by maxwofford — APPROVED** [review]

**Comment by albertchae** [comment]
Removed from prod in heroku too
image

**Comment by albertchae** [comment]
The prod builds are still coming in around 400 MB, so I'm going to try purging the build cache with `heroku builds:cache:purge -a bank-hackclub` (from https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache)

**Comment by albertchae** [comment]
Looks like purging the cache worked

https://dashboard.heroku.com/apps/bank-hackclub/activity/builds/6c2f7c4b-9d74-49f7-a45c-e9deb4f1627c

```
-----> Compressing...

       Done: 243.5M
```

**Pull request merged**
