### PR TITLE
Attempt to add source version for preview deploys via buildpack

### PR DESCRIPTION
**Pull request by maxwofford**
If this works, the preview deploy in this PR should have a `.source_version` file in the root of the project.

### CODE REVIEW

**Comment by maxwofford** [comment]
```sh
❯ heroku run rails c -a bank--pr-1991
irb(main):001:0> `cat .source_version`
=> "a33f99964e43548275c5f7f1547bd02742f7ee8e\n"
```

**Comment by kunalbotla** [comment]
image
I seem to be getting an error on `/faq`

**Comment by maxwofford** [comment]
Screen Shot 2021-11-08 at 18 57 06

Build time is missing, but hash shows up now

**Comment by garyhtou** [comment]
ayyy cool beans, i love this

**Pull request merged**
