### PR TITLE
Admin: filter HCB codes by 'has receipt?'

### PR DESCRIPTION
**Pull request by cjdenio**

### CODE REVIEW

**Comment by cjdenio** [comment]
Actually, hang on– I'm gonna make some changes

**Review by exu3 — COMMENTED** [review]
Would it make sense to put this filter on the Admin Ledger page rather than the HCB CODES page? The HCB CODES page has a lot of irrelevant stuff (eg. unsubmitted donations); I'm not sure it's very useful given the Ledger page exists.

**Comment by cjdenio** [comment]
Hmm, I think it makes more sense to have it here because receipts are uploaded to HCB codes.

**Review by exu3 — APPROVED** [review]
LGTM!

**Pull request merged**
