### PR TITLE
Beneficiaries of transfers are visible in transparency mode

### PR DESCRIPTION
**Pull request by exu3**
Closes #2861 

(Best reviewed with whitespace changes hidden.)

### CODE REVIEW

**Comment by maxwofford** [comment]
This looks like it hasn't been touched in a while– is it ready for a review?

**Comment by exu3** [comment]
It is.

**Review by maxwofford — COMMENTED** [review]
Should we show the search bar like this?

**Comment by exu3** [comment]
Approved irl by @maxwofford

**Pull request merged**
