### PR TITLE
Clarify that the donation form is in USD

### PR DESCRIPTION
**Pull request by sampoder**
It would be cool if I could change this as a user, to avoid situations such as https://bank.hackclub.com/donations/start/the-innovation-circuit

### CODE REVIEW

**Review by exu3 — COMMENTED** [review]
Good call, thanks for the PR!

Thoughts on adding this clarification just on organizations that are not US-based? I think the currency can just be assumed for US-based organizations.

You can use the `<% if !@event.country_us? %>` condition (example on line 33).

https://github.com/hackclub/bank/blob/d6f6448ee838594025ca3f82a4155ec970482ff3/app/views/donations/_donation_form.html.erb#L33

**Comment by sampoder** [comment]
done!

**Review by exu3 — APPROVED** [review]
Thanks Sam!

**Comment by garyhtou** [comment]
Thanks for the PR @sampoder, and thanks for reviewing @exu3!

**Pull request merged**
