### PR TITLE
Handle missing `email` param for login

### PR DESCRIPTION
**Pull request by northeastprince**
Didn't catch potential additional error coming with #3971.

### CODE REVIEW

**Comment by northeastprince** [comment]
Feel free to merge upon approval.

**Comment by garyhtou** [comment]
See https://github.com/hackclub/bank/commit/df437f92a9b06bdef5aa27ce4f9d1a4b787c4a39#r118089754

**Comment by garyhtou** [comment]
Another thing I wanna mention too is that we can use strong params in the controller to handle this

**Comment by northeastprince** [comment]
Yeah, but that only protects against mass assignment, not omitting a required attribute.

**Comment by garyhtou** [comment]
> Yeah, but that only protects against mass assignment, not omitting a required attribute.

With strong params, you can use [`require`](https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-require). It'll raise an `ActionController::ParameterMissing` if the parameter was omitted.

Example:
image

**Comment by garyhtou** [comment]
image

**Pull request merged**
