### PR TITLE
Drop unencrypted columns on AchTransfer and GSuiteAccount

### PR DESCRIPTION
**Pull request by albertchae**
Follow up to https://github.com/hackclub/bank/pull/2886

Because these columns are ignored, it is safe to drop them

### CODE REVIEW

**Comment by kunalbotla** [comment]
will this retain account numbers from previously processed ACH transfers? i think it's important to keep them visible for reference by organizations

**Comment by albertchae** [comment]
Hey @kunalbotla This PR is only to drop the unencrypted column. We're still keeping the data (but encrypted in `account_number_ciphertext`). This is the next step in this process https://github.com/ankane/lockbox#migrating-existing-data

**Review by maxwofford — APPROVED** [review]
LGTM!

**Comment by albertchae** [comment]
Because there is still some risk to any column dropping, I created backup `b549` on heroku just in case. Merging now

**Pull request merged**
