### PR TITLE
"Event not found" -> "Organization not found"

### PR DESCRIPTION
**Pull request by cjdenio**
I think the "event" terminology is a little confusing here, and it seems like "project" is being used more now.

Screen Shot 2022-06-16 at 8 11 31 PM

### CODE REVIEW

**Review by exu3 — COMMENTED** [review]
Good call! I think we should use "organization" instead of "project" to be consistent with the Bank marketing page (https://github.com/hackclub/site/pull/458)

**Comment by cjdenio** [comment]
Oh hmm. "Project" is already used a bunch throughout the UI (but so is "Organization").

Screen Shot 2022-06-16 at 9 51 53 PM
Screen Shot 2022-06-16 at 9 51 01 PM
Screen Shot 2022-06-16 at 9 50 54 PM

I guess I'd think of it as "You're signing up your organization for a project on Bank", so the thing on Bank is a "project" but an "organization" is using Bank. Not sure.

**Comment by garyhtou** [comment]
I think we're trying to move towards using "organization" in place of "event" and "project". if you see any instances of "event" or "project", feel free to switch them over (especially in the UI)

**Review by garyhtou — APPROVED** [review]
go for it! thanks :)

**Pull request merged**
