### PR TITLE
Pass user birthdays to Stripe

### PR DESCRIPTION
**Pull request by cjdenio**
part of #2775

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]

**Comment by garyhtou** [comment]
Just wondering, do we know how Stripe will behave if we pass a `dob` that's < 18 years old?

**Comment by maxwofford** [comment]
@garyhtou I totally didn't think of that. @cjdenio – could you test this out in prod? We might need a conditional to skip providing this info in that case.

**Comment by maxwofford** [comment]
I just updated my own & it didn't stop me. Will report if my account is deactivated.

Screen Shot 2022-10-05 at 15 40 13

**Comment by exu3** [comment]
There are cardholders on Stripe currently that we have manually entered in DOBs for that are under 18. For example: https://dashboard.stripe.com/issuing/cardholders/ich_1LlBcYFSaumjmb9r2A7Utnps

**Comment by cjdenio** [comment]
It doesn't work if you're under 13:

Screen Shot 2022-10-05 at 3 41 15 PM

**Comment by maxwofford** [comment]
@cjdenio I don't think we have anyone under 13 on Bank, but go ahead and add a condition w/ comment that links to this thread for context.

**Pull request merged**
