### PR TITLE
Change transactions icon to list

### PR DESCRIPTION
**Pull request by malted**
As per @dwahbe's feedback.

image

### CODE REVIEW

**Comment by sampoder** [comment]
I feel like the old transaction logo makes more sense, no?

**Comment by malted** [comment]
How so?

**Comment by sampoder** [comment]
It communicates what type of items I'll be seeing on the page and it also looks nicer. A list icon could be used for anything so it isn't telling me much (other than that there will be a list of transactions, which is implied by it being plural imo, and is a bit bland.

**Comment by sarthaktexas** [comment]
i'm w sam

**Comment by malted** [comment]
hm the thing that doesn't make sense for me is the arrows around the dollar sign with the current one - circular arrows make absolutely no sense here.

**Comment by dwahbe** [comment]
I think the tricky thing using that icon for the Transactions tab is that we also use it to convey that a donation is a recurring donation.

Screenshot 2024-04-29 at 12 57 25 PM

**Comment by garyhtou** [comment]
Neither are the right icon. Let's design a new icon, if necessary

**Pull request closed without merging**
