### PR TITLE
update FS letter to HCB email

### PR DESCRIPTION
**Pull request by rluodev**
This still keeps Mel's name and signature while we figure out who/what to put on the signature section.

This PR will close #4657 once merged.

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
lgtm, thanks!

**Review by sarthaktexas — APPROVED** [review]
lgtm!

**Review by hackliv — APPROVED** [review]

**Comment by rluodev** [comment]
@garyhtou can u pls approve thx

**Review by garyhtou — APPROVED** [review]
Let's merge this!

**Pull request merged**
