### PR TITLE
Update webauthn for openssl 3

### PR DESCRIPTION
**Pull request by albertchae**
Ran `bundle update webauthn`

I believe the `ruby:3.1.4` only has openssl 3 and greater, so we need to
make this change before moving to ruby 3.1

### CODE REVIEW

**Comment by albertchae** [comment]
I tested I was able to login with my yubikey on the review app, so I think this is good to go.

**Comment by albertchae** [comment]
@maxwofford should be safe to merge after review, although I'd check security key login on prod after deploy just to be safe

**Comment by albertchae** [comment]
Per https://github.com/hackclub/bank/pull/3996#issuecomment-1601215792, I reset this branch to just be the webauthn changes. I'll reopen that branch after we merge this one

**Review by maxwofford — APPROVED** [review]

**Comment by maxwofford** [comment]
I can confirm webauthn works in prod after merge!

**Pull request merged**
