### PR TITLE
Current user's comments are highlighted

### PR DESCRIPTION
**Pull request by maxwofford**
Screen Shot 2022-01-06 at 13 30 09
Screen Shot 2022-01-06 at 13 30 05

Comments from the current user now have a faint blue background

### CODE REVIEW

**Comment by maxwofford** [comment]
This also gives a faint heighlight to the current user's avatar across every use of the `avatar_for` method:

Screen Shot 2022-01-06 at 13 43 13
Screen Shot 2022-01-06 at 13 42 56

And adds a tooltip for the same avatars to clearly show it's the currently logged in user:

Screen Shot 2022-01-06 at 13 51 39
Screen Shot 2022-01-06 at 13 51 31
Screen Shot 2022-01-06 at 13 51 04

**Comment by maxwofford** [comment]
@eilla1 I'm not attached to these changes, but this was the original reasoning:

Screen Shot 2022-01-06 at 13 56 49

I like how GitHub makes it so clear which comments/actions came from you vs other users.

**Review by exu3 — APPROVED** [review]
Cool! I like these changes. Very klassy.  The avatar outline is a bit subtle though; I don't think I'd be able to tell unless it was pointed out to me but I don't think that's necessarily a bad thing.

Screen Shot 2022-01-06 at 11 08 03 AM

**Comment by maxwofford** [comment]
@eilla1 Do you have thoughts on how to make it more apparent which avatar is your own user? I totally agree & am all ears.

**Comment by exu3** [comment]
https://github.com/hackclub/bank/pull/2188#issuecomment-1006854219 Maybe a badge? I can't think of a good icon off the top of my head though.

I think it's also fine to not clearly indicate the current user's avatar because I'd assume that everyone has different avatars so it wouldn't be too hard to distinguish yourself from your teammates.

**Comment by maxwofford** [comment]
Merging this for the improvement to the comment designs. The avatar stuff is on the subtle side, but I don't think it degrades the experience for anything.

**Pull request merged**
