### PR TITLE
Bank can check own version hash

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
@eilla1 @kunalbotla @garyhtou if bank can know details like what version of deploy it's at & when the current version was deployed at, is there anything cool we can do with it?

**Comment by kunalbotla** [comment]
i mean it'd be cool. it used to have it before this redesign iirc

**Comment by exu3** [comment]
is the `Build 3d3b438 from about 6 hours ago.` different from what you're describing? or are you referring to the SemVer version numbers?
Screen Shot 2021-10-01 at 6 45 28 PM 

Either way I think it'd be cool to have in the footer on certain pages and maybe some flavor text too

**Comment by maxwofford** [comment]
Doesn't seem like this is needed then!

**Pull request closed without merging**
