### PR TITLE
Proposal: After saving updates to user profile, redirect to root (/)

### PR DESCRIPTION
**Pull request by thesephist**
## Problem

When new team members are first invited to an event, a part of their onboarding process is to create / update their user information. Currently this is just done under `/users/:id/edit`, which means after the (probably new) user updates their profile, they sit on the profile view and it's not intuitive how to get to the events page.

## Proposal

When the user updates their profile, we redirect them to their index page `/`. This is a _little_ weird if they've got multiple events under their account, but imo not much more weird than leaving them on the profile page. And I think the main benefit is that when new users get onboarded, they don't get super confused immediately. That outweighs the slight weirdness imo.

At some point we should re-do the onboarding, but for now I think this is a net improvement.

### CODE REVIEW

**Comment by thesephist** [comment]
It would be nice if we could detect if a session is their first-ever session. But I don't if that's possible or how easy that is yet....

**Comment by thesephist** [comment]
This addresses #219

**Review by lachlanjc — APPROVED** [review]
Big agree!

**Comment by tmb** [comment]
I'm into this—we could probably figure out first-ever session based on the `created_at` of a user.. if it's within 10 minutes or something like that then redirect to root

**Pull request merged**
