### PR TITLE
Put reserved slugs on their own lines

### PR DESCRIPTION
**Pull request by malted**
Simplifies diffs.

Suggested by @garyhtou [here](https://github.com/hackclub/hcb/pull/5396#pullrequestreview-1917767173).

### CODE REVIEW

**Review by garyhtou — COMMENTED** [review]
Thanks! Can you convert it into the percent string syntax?

```ruby
config.reserved_words = %w[
  new
  edit
  index
]
```

**Comment by garyhtou** [comment]
(vscode's multi cursor or vim is a great way to make those edits!)

**Review by malted — COMMENTED** [review]
Convert to percent string syntax

**Comment by malted** [comment]
Done!

**Review by garyhtou — APPROVED** [review]
Great! ty

**Pull request merged**
