### PR TITLE
Add missing receipt count badge to nav

### PR DESCRIPTION
**Pull request by cjdenio**
Painstakingly tested across light/dark mode, and desktop/mobile.

Screen Shot 2022-05-17 at 11 42 09 PM
Screen Shot 2022-05-17 at 11 42 28 PM

### CODE REVIEW

**Review by maxwofford — COMMENTED** [review]
Love this addition!

This may have to be updated with similar transaction logic to https://github.com/hackclub/bank/pull/2568– the implementation I'm reading in this PR doesn't filter out declined transactions.

**Comment by cjdenio** [comment]
Yeah, good point– I'll wait 'til #2568 is merged

**Review by maxwofford — APPROVED** [review]
Great! This looks like the count should work, but I'm a little worried this query is going to slow down loading for some users. Try it on `max@hackclub` as an example case. If it's slow, want to try refactoring it? If it's fine, go for merge!

**Comment by maxwofford** [comment]
Hmmmm, looking back at this, maybe the fix is to make this async? In a perfect world it loads instantly, but in a less-than perfect world the pages still load quickly even if the notification pops up after a little bit.

We could make a missing receiptable service that handles these types of things, then make a new endpoint that serves it's data.

**Pull request closed without merging**
