### PR TITLE
Events aren't required to have partners

### PR DESCRIPTION
**Pull request by maxwofford**
This is just a step towards a larger change of removing the complexity that the `Partner` model adds

### CODE REVIEW

**Comment by maxwofford** [comment]
This mostly removes requirements in the codebase for events to have partners. New events will be created without partners.

This also adds `OneTimeJobs::RemoveAllPartnerAssociations` to remove partners from orgs that we can run in the future.

Would love your thoughts on this @garyhtou – I'm a bit rusty on how partners work.

**Comment by albertchae** [comment]
Per 5/23 meeting with @maxwofford , I'm taking over this PR

**Comment by albertchae** [comment]
```
Event.all.map {|e| e.partner_id}.tally
=> {1=>2121, 3=>45, 2=>1}
```

1 is HCB, 2 is givebutter, 3 is demo. So it seems like this is essentially a dead feature.

@garyhtou can you double check if there's anything else we need to worry about here?

**Review by garyhtou — APPROVED** [review]
That looks good. It's a dead feature and all the partner data can be nuked

**Review by albertchae — APPROVED** [review]
@maxwofford this one should be good to go, feel free to merge whenever

**Comment by maxwofford** [comment]
Once this deploys I'll run `OneTimeJobs::RemoveAllPartnerAssociations`

**Pull request merged**
