### PR TITLE
Receipts → Feedback

### PR DESCRIPTION
**Pull request by kunalbotla**
Updating the bell/notification icon to be the new receipts icon

image

### CODE REVIEW

**Comment by hackliv** [comment]
I actually was thinking of removing that entirely since it's repetitive. Thoughts?

**Comment by garyhtou** [comment]
yeah i agree, i think we should remove, but then put the feedback button in its place

**Comment by kunalbotla** [comment]
i like that; i'll make that change

**Comment by kunalbotla** [comment]
updated! 
image

**Review by garyhtou — CHANGES_REQUESTED** [review]
please assign for review before merging next time! (no need to revert)

Can we remove the Feedback navigation dock item? (in another pr)
image

**Comment by kunalbotla** [comment]
sorry! i thought it was small enough to merge the change based the original review. i'll make that new pr

**Pull request merged**
