### PR TITLE
Edits to generated PDFs (fiscal sponsorship confirmation + ach transfer confirmation)

### PR DESCRIPTION
**Pull request by garyhtou**
ACH Transfer | Fiscal Sponsorship Confirmation
-|-
Screenshot 2021-04-08 234957|Screenshot 2021-04-08 180157

### CODE REVIEW

**Comment by maxwofford** [comment]
Thank you so much @garyhtou, the spacing was killing me

**Comment by garyhtou** [comment]
Yeah np, @maxwofford! Does pdf generation not work on review dynos? (I'm getting 500 - works fine on local dev). Is there a way to see the rails logs for a review dyno?

Also, it's weird how the pdfs generated on local dev vs. prod have different font sizes/spacing

**Comment by garyhtou** [comment]
PDF generation doesn't work on review dynos because the `wkhtmltopdf` buildpack isn't included on deploy. Fixed here #1442 

And the difference in `wkhtmltopdf` versions between the buildpack and gemfile probably explains the different font sizes/spacing

**Comment by garyhtou** [comment]
rebasing onto `update-buildpacks` (#1442) to get `wkhtmltopdf` in review dyno

**Comment by garyhtou** [comment]
Yayy! Pdfs are now fixed to be one page, and are identical when generated on dev and review dyno (hopefully that'll be the case for prod)

ACH Transfer | Fiscal Sponsorship Confirmation
-|-
Screenshot 2021-04-08 234957|Screenshot 2021-04-08 180157

**Review by motdotla — APPROVED** [review]

**Pull request merged**
