### PR TITLE
QoL improvements to new team page

### PR DESCRIPTION
**Pull request by malted**

### CODE REVIEW

**Review by cjdenio — DISMISSED** [review]

**Review by cjdenio — CHANGES_REQUESTED** [review]
I'm running into a few layout issues on mobile:
Screenshot 2024-02-13 at 4 51 38 PM

**Review by garyhtou — APPROVED** [review]
good to merge!

When the name wraps, the email/phone icons float out to the right a bit too far. See if you can address this in a separate PR.
image

**Comment by garyhtou** [comment]
Also, maybe we can try something like this for non-admins
image

**Comment by garyhtou** [comment]
Please update the PR description with screenshots!

**Comment by malted** [comment]
> Also, maybe we can try something like this for non-admins image

that looks good but I'm going to put the user role there so it would be quite temp.

**Comment by garyhtou** [comment]
Imma merge this!

**Comment by garyhtou** [comment]
@malted please update the PR description with screenshots!

**Pull request merged**
