### PR TITLE
Remove several services and jobs using selenium

### PR DESCRIPTION
**Pull request by albertchae**
Because HCB is no longer using SVB and its interaction with SVB was via
selenium, we can remove code that was dependent on selenium and
eventually remove the heroku buildpack to save slug space.

This commit removes several services and their corresponding jobs that
relied on `Shared::Selenium::LoginToSvb`

AFAICT, none of these jobs were in the current set of sidekiq cron jobs
https://github.com/hackclub/bank/blob/main/config/schedule.yml

### CODE REVIEW

**Comment by albertchae** [comment]
Open questions:

1. https://github.com/hackclub/bank/blob/3b924b72c083a2eca318856a736eea0cdaacd9a5/app/services/fee_reimbursement_service/nightly.rb is using `LoginToSvb` and appears to be scheduled here https://github.com/hackclub/bank/blob/3b924b72c083a2eca318856a736eea0cdaacd9a5/config/schedule.yml#L43-L47. Is this safe to remove?

2. There seems to be a page for viewing and creating selenium sessions https://bank.hackclub.com/admin/selenium_sessions which eventually uses https://github.com/hackclub/bank/blob/3b924b72c083a2eca318856a736eea0cdaacd9a5/app/services/selenium_service/parse_cookies.rb. Is this safe to remove?

**Comment by cjdenio** [comment]
1. the `fee_reimbursement_nightly_job` is currently disabled in production because it hasn't been switched from SVB to Increase. Please do remove all the Selenium code, but keep the job/service there for when we do rewrite it
2. All of the `SeleniumSession` stuff looks to not be in use, so I'd say it's safe to remove.

**Comment by garyhtou** [comment]
> All of the `SeleniumSession` stuff looks to not be in use, so I'd say it's safe to remove.

Yup, that's right! Everything related to `SeleniumSession` can be removed. This was added back when Selenium had a hard time logging into SVB by itself. We had to manually login on a proper browser, grab the cookie, then give it to bank. it was jank as it gets lol

**Comment by cjdenio** [comment]
Updating with rebase to pull in https://github.com/hackclub/bank/pull/3713 changes

**Comment by albertchae** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3695** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3695" target="_blank">Graphite</a>  👈
    * **PR #3741** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3741" target="_blank">Graphite</a> 
      * **PR #3742** <a href="https://app.graphite.dev/github/pr/hackclub/bank/3742" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/hackclub/bank/3695?utm_source=stack-comment).

**Comment by albertchae** [comment]
Thanks for the rebase @cjdenio

**Review by maxwofford — APPROVED** [review]
This looks good, but want to flag that you should check the sidekiq interface first-- they seem to have drifted from the yaml config.

**Review by cjdenio — APPROVED** [review]

**Comment by albertchae** [comment]
> This looks good, but want to flag that you should check the sidekiq interface first-- they seem to have drifted from the yaml config.

Do you mean with https://bank.hackclub.com/sidekiq/cron? I just did (after sorting `schedule.yml` with `yq` https://mikefarah.gitbook.io/yq/operators/sort-keys), and they look the same to me, except that `fee_reimbursement_nightly_job` is still disabled. 
image

I'm surprised that https://github.com/hackclub/bank/pull/3713 merging wouldn't have turned that back on and also that `/sidekiq/cron` doesn't always reflect the latest state of `schedule.yml` (unless someone manually disabled it since the last deploy). Any idea what's going on there? Also @cjdenio is it safe to enable that job manually?

**Comment by cjdenio** [comment]
OH that job should definitely be enabled. Thanks for catching that!

I suspect that Sidekiq doesn't update if you *remove* the `status` key, only if you explicitly set it to `enabled`/`disabled`

**Comment by albertchae** [comment]
Sorry forgot to tag @maxwofford for https://github.com/hackclub/bank/pull/3695#issuecomment-1499302266

But since the changes to schedule.yml by this PR are only comments (https://github.com/hackclub/bank/pull/3695/files#diff-18c4a92c666266e8bead5b6ddb034501022877cdf773c0d337499ed0a7f6d341), I'm going to proceed with merging and address follow ups

**Pull request merged**
