### PR TITLE
Account balance in transaction list

### PR DESCRIPTION
**Pull request by tmb**
image

A few issues:
* Balances are screwed up on events that have errors with some fee reimbursements (ones i discovered: Windy City Hacks, Spectra)
* They all go sumo if you expand one that it doesn't like (see: 
image)

@MaxWofford will work with you on this tomorrow along with the other PR

### CODE REVIEW

**Comment by lachlanjc** [comment]
Mentioned this to @tmb but putting here for other team members.

Though I wasn’t there for the discussion of this feature, personally I’d rather not have it. For someone coming from a background of accounting systems & books (hi Zach!), I’m sure this is great, but for a high schooler without accounting knowledge, this is added complexity & kind of confusing.

I think a good balance to strike would be having this in the CSV export—if you’re doing real accounting/financial analysis, you probably want a full spreadsheet anyway, but the website is the overview I check on my phone, & a balance column isn’t helpful to me. (Again, it probably is for some, but not the majority of high schoolers.) I’ll also note that I’ve never once used the export CSV option as an organizer, though I am glad we have it.

**Comment by zachlatta** [comment]
Looping in @thesephest to provide input here.

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by maxwofford** [comment]
Doesn't look like @thesephist was tagged... adding now

**Comment by thesephist** [comment]
Sorry, just getting around to these.

I agree with @lachlanjc that it unnecessarily clutters up the UI most of the time, but I do think this info should be available without doing a data export of some sort. What if we showed the balance before/after a transaction in the details page for the tx? We could also put it behind a toggle/option in the header of the tx list.

At any rate, doesn't seem like it's super urgent, so we should come back to it after MLH stuff is figured out.

**Comment by thesephist** [comment]
IRL discussion with @tmb: we're going to not show balance in the transactions list in the web UI, but add balances on the CSV export.

**Pull request closed without merging**
