### PR TITLE
Add option to bypass authentication in development

### PR DESCRIPTION
**Pull request by northeastprince**
No more searching for login codes on every deploy!

### CODE REVIEW

**Comment by northeastprince** [comment]
Not sure if there's a better way to implement this on the frontend side without having a separate email field.

**Comment by northeastprince** [comment]
.deploy atm3

**Review by garyhtou — CHANGES_REQUESTED** [review]
Since staging contains a copy of the production database it must have authentication! We like to keep staging as similar to production as possible

**Comment by maxwofford** [comment]
I'd kinda like to still have authentication in development– all the recent login improvements have come from devs dealing with this and getting frustrated, which led to improvements to the signup flow. I'm worried if we alleviate that pain just for us we're going to leave that burden on regular users.

**Comment by northeastprince** [comment]
Ok, no problem! Thought it'd be a convenient thing to have, but that's a good point.

**Comment by maxwofford** [comment]
@northeastprince I can def see scenarios this would be nice though! thoughts on having an env var that allows bypass, then check for env var AND that we're running in dev?

**Pull request closed without merging**
