### PR TITLE
Fix the Wrapping on Mobile

### PR DESCRIPTION
**Pull request by clarencejychan**
image
image

Fixes #1981

### CODE REVIEW

**Comment by clarencejychan** [comment]
Didn't see @eilla1 's comments on the issue. Going to checkout FF and Safari (although not sure how to do it with Safari) maybe browserstack?

**Comment by maxwofford** [comment]
We have a browserstack account if you need it– DM me on Slack for access

**Comment by clarencejychan** [comment]
I think we're actually good for now since @eilla1  checked out the Safari version already but I will in the future. Thanks!

**Review by maxwofford — APPROVED** [review]
LGTM!

**Pull request merged**
