### PR TITLE
[Reimbursements] Provide Fallback for Email Invites

### PR DESCRIPTION
**Pull request by sampoder**
Edge case where organiser uses the public form.

### CODE REVIEW

**Comment by sampoder** [comment]
just gotta check this works locally

**Comment by sampoder** [comment]
Screenshot 2024-04-03 at 6 47 25 PM

fixes it!

**Comment by garyhtou** [comment]
wasn't this fix for an invite, not an expense approval?

**Comment by sampoder** [comment]
Sorry yep! Just retested, confirmed it did fix the bug:

Screenshot 2024-04-03 at 11 20 58 PM

**Pull request merged**
