### PR TITLE
Add break-word to sidebar so longer names wrap

### PR DESCRIPTION
**Pull request by InternetRamen**
image

### CODE REVIEW

**Comment by maxwofford** [comment]
Hmmmm... mixed feelings about this because it wraps user content. If we mess with our own interface that's one thing, but I don't want to mess with the name the user chose. What does ellipse or hiding overflow look like?

**Review by maxwofford — APPROVED** [review]
Going to approve this despite my comment because I think this is an improvement over the current setup which kinda looks broken.

**Comment by northeastprince** [comment]
Maybe we could extend the sidebar (up to a point) and/or lower the font size based on the length, and then just truncate it (... at the end) as a last resort? The current change is definitely the lesser of 2 evils but if there's a relatively straightforward way to implement either of these options that'd be way better.

**Comment by InternetRamen** [comment]
Hmm, good points. I'm gonna keep working on this.

**Comment by maxwofford** [comment]
@InternetRamen cool if we merge this? Doesn't mean you can't make the other improvements, but I'd love to get this issue fixed so navs don't break pages.

**Comment by InternetRamen** [comment]
> @InternetRamen cool if we merge this? Doesn't mean you can't make the other improvements, but I'd love to get this issue fixed so navs don't break pages.

Yup, just saw this but. I'll go ahead and merge

**Pull request merged**
