### PR TITLE
Use new transaction engine for stats endpoint

### PR DESCRIPTION
**Pull request by garyhtou**
Updated the endpoint to be compatible with the original schema and hackclub.com/bank:

- adding `revenue` (fee revenue)
- return `events` as an array of `{ created_at: 1530053412}`

Also updated the admin dashboard's "#____ in transaction & counting..." to use the new engine.

### Tested locally:
[hackclub.com/bank](https://hackclub.com/bank) | bank admin
-|-
image | image

### CODE REVIEW

**Comment by garyhtou** [comment]
#1555

**Review by motdotla — APPROVED** [review]

**Comment by motdotla** [comment]
@garyhtou I actually had to revert this. I should have double checked it locally first. The method or variable `tx_last_year` was missing.

**Comment by motdotla** [comment]
When you get a chance can you re-submit the PR

**Comment by motdotla** [comment]
Here's the related Airbrake https://heroku-app97991095.airbrake.io/projects/288439/groups/3014930699832228273?tab=overview

**Comment by garyhtou** [comment]
my bad! fixed in #1616

for some reason, this pr didn't pull in Max's commit which included the `tx_last_year` variable

**Pull request merged**
