### PR TITLE
Simplify Address Generation UI for Receipt Emails

### PR DESCRIPTION
**Pull request by sampoder**
The new receipt emails are sick! Like super sick! It's really fun to just click the button and keep generating more and more and more... 

One thing though was getting to the page where you did that felt a little clunky and like a long process. At least in my personal opinion. 

So I made this PR which simplifies things a little and puts all of the UI on the settings page:

https://github.com/hackclub/hcb/assets/39828164/82477989-e26e-48c4-a454-a3fa39709681

Would appreciate if someone could sanity check the Turbo stuff for me.

I also had a couple of other ideas:

a) what if we generated little mini profile pictures on the side? to make each animal feel like a character... just imagine you're sending your receipts to this friendly little Quokka:

image
 
b) what if everyone had a mailing address by default? we could probably make a one-time job to generate a bunch. is there any harm to doing that? I feel like it'd reduce the friction for people to get started.

### CODE REVIEW

**Comment by sampoder** [comment]
Rubocop , RSpec & Zeitwerk are failing on the `convert-html-receipts-to-pdf` branch, I'm gonna avoid touching those in this branch (might make a separate PR for Rubocop; RSpec & Zeitwerk are credential-related and I think they can be resolved by merging main into the branch).

**Comment by YodaLightsabr** [comment]
The visual side of this looks great! I think there were some other concerns with doing it in the settings page, though, mainly it being possibly confusing for users that don't know what it is.

Edit: also iirc the tests are failing because I haven't updated the tests for the receipt inboxes.

**Comment by sampoder** [comment]
Thoughts on keeping the modal then for initial setup? We could use that to give people the run down.

**Comment by sampoder** [comment]
Alright, what I've done is I've kept the separate page for your first email address (what shows up when you click the big blue button):

Screenshot 2023-11-28 at 10 05 11 AM

After you click activate it redirects you back to your settings page.

As an extension to this it might be nice to add some fancy graphics / screenshots to help folk understand what to do.

**Pull request merged**
