### PR TITLE
(WIP) Upgrade to Rails 6

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
I’d love to get this merged so we could use view components :)

They’re possible to implement in v5, but better supported in v6. GitHub has been using them for their UIs for the last 1.5 years & I’d love to try them out instead of faking the idea with helpers. https://github.com/github/view_component

**Comment by maxwofford** [comment]
@lachlanjc should I make this priority today? What'll be most helpful for you?

**Comment by lachlanjc** [comment]
It’s not going to change my workflow significantly, so work on whatever makes sense, but I’d love to do this in the relatively near future.

**Comment by lachlanjc** [comment]
You’re doing so great 👏🤩

**Comment by maxwofford** [comment]
Screenshot 2020-07-02 13 19 46

**Pull request merged**
