### PR TITLE
add pending reimbursement cards on homepage

### PR DESCRIPTION
**Pull request by rluodev**
Screenshot 2024-03-04 at 11 11 23 AM

Screenshot 2024-03-04 at 11 11 26 AM

A nice way to present pending reimbursements to users up front - maybe an easier flow, since when a new user signs in for the first time their draft reimbursement report will be right up front and center.

### CODE REVIEW

**Comment by sampoder** [comment]
Chatted in DMs! Plan is to work on this post-launch this weekend

**Comment by rluodev** [comment]
arrrgh this branch is now broken lmao

**Comment by garyhtou** [comment]
oh boyyyyy lol
image

**Comment by sampoder** [comment]
Thanks for all the great work on this! Looking at the merge conflicts, I'm going to close this PR. I'd recommend working in a fresh branch and porting over code if you're still interested in working on this.

**Pull request closed without merging**
