### PR TITLE
Virtual cards are visually distinct

### PR DESCRIPTION
**Pull request by maxwofford**
Reverts hackclub/bank#554

### CODE REVIEW

**Comment by maxwofford** [comment]
before: Screenshot 2020-03-27 18 52 39

after: 
Screenshot 2020-03-27 19 02 25

**Comment by maxwofford** [comment]
Screenshot 2020-03-28 00 04 52

I'm getting close to how I want it to look, but I'm stuck on positioning. @lachlanjc how can I fix the grid view on medium screens?

Screenshot 2020-03-28 00 04 15

**Comment by maxwofford** [comment]
Screenshot 2020-03-29 20 02 44
newest WIP screenshot– canceled and suspended cards are now grayed out

**Comment by maxwofford** [comment]
Also, loading the 'show' page for cards is ~3-4 times faster (was ~9-10 seconds, now ~3-4)

**Comment by maxwofford** [comment]
Screenshot 2020-03-29 20 46 48
view of a suspended digital card ^

**Comment by lachlanjc** [comment]
Sorry, haven’t looked at this. Do you still want my attention/where?

**Comment by maxwofford** [comment]
Couldn’t figure out how to resize the card grid to transition to mobile with the new card sizes. Hoping to get some help on that.

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Pull request merged**
