### PR TITLE
Add validates_email_format_of to user.email

### PR DESCRIPTION
**Pull request by albertchae**
As part of https://github.com/hackclub/bank/issues/2415, we will be removing
`email` from `organizer_position_invites`, which was using this
`validates_email_format_of` validator. However, because we will be using
email directly off `organizer_position_invite.user`, I noticed that the
same email validation wasn't being run on `user`, so this PR adds that.

Fortunately it looks like there was only one existing user with an
invalid email, so it wasn't a widespread problem.

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Chatted over our call today, but for posterity this is good to merge & we'll still have the User's `paper_trail` log of email changes to tell where the first invite when out to.

**Comment by albertchae** [comment]
@maxwofford just to clarify, this PR doesn't remove email off `OrganizerPositionInvite` yet, but it sets us up to do so because the validation on email will be run directly on `user` now

I noticed one user fails the validation after adding this (I found this by running `User.all.filter {|u| !u.valid?}` in a local console). This is user id: 2848 with email `gary+edgeSameAmountDifferentOrg1` @garyhtou is this by any chance you? I was wondering if we should delete this user or set the email to something valid

**Comment by garyhtou** [comment]
yes! that was me, go ahead and do whatever you'd like with that user

**Comment by albertchae** [comment]
@garyhtou I tried to change the email to `gary+edgeSameAmountDifferentOrg1@hackclub.com` but apparently that was already taken by the next user in the db 2849 😆 so I ended up just destroying it
```
irb(main):007:0> User.find(2848)
=> #<User id: 2848, api_access_token: nil, created_at: "2022-01-23 12:06:22.371350000 +0000", updated_at: "2022-01-23 12:06:22.371350000 +0000", email: "gary+edgeSameAmountDifferentOrg1", full_name: nil, phone_number: "", admin_at: nil, slug: "gary-edgesameamountdifferentorg1", pretend_is_not_admin: false, sessions_reported: false, phone_number_verified: false, use_sms_auth: false, webauthn_id: nil, session_duration_seconds: 2592000, birthday: nil>
irb(main):008:0> User.find(2848).destroy!
What is your email (used by PaperTrail to record who changed records)? REDACTED
Thank you, Albert Chae! Have a wonderful time!
=> #<User id: 2848, api_access_token: nil, created_at: "2022-01-23 12:06:22.371350000 +0000", updated_at: "2022-01-23 12:06:22.371350000 +0000", email: "gary+edgeSameAmountDifferentOrg1", full_name: nil, phone_number: "", admin_at: nil, slug: "gary-edgesameamountdifferentorg1", pretend_is_not_admin: false, sessions_reported: false, phone_number_verified: false, use_sms_auth: false, webauthn_id: nil, session_duration_seconds: 2592000, birthday: nil>
```

**Pull request merged**
