### PR TITLE
Add password to example development env DATABASE_URL

### PR DESCRIPTION
**Pull request by polypixeldev**
## Summary of the problem

When creating a new codespace, the container build currently fails due to the database setup commands in `.devcontainer/boot.sh` not being able to connect to the database without a password provided.

## Describe your changes

I added the default postgres password (`postgres`) to the example database connection URL in `.env.development.example`, which is also the password specified in `.devcontainer/docker-compose.yml`. The codespace build succeeds after this change since it copies the values from the `.env.development.example` to `.env.development`.

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
Looks good to me!

**Comment by garyhtou** [comment]
Can either of yall please make sure this new `.env.development.example` works with the existing `.docker_dev_setup.sh` script?

**Comment by garyhtou** [comment]
I believe `.docker_dev_setup.sh` should work fine since we've got <a href="https://hub.docker.com/_/postgres#:~:text=PostgreSQL%2010%2B).-,POSTGRES_HOST_AUTH_METHOD,-This%20optional%20variable">POSTGRES_HOST_AUTH_METHOD</a> set in `.docker_compose` which should allow connections without authentication (e.g. a password; or the right password)

**Comment by polypixeldev** [comment]
Dev setup script run without issues!

**Comment by sampoder** [comment]
Awesome!

**Review by garyhtou — APPROVED** [review]

**Comment by garyhtou** [comment]
Great! thank you!

**Pull request merged**
