### PR TITLE
Add logo and improve performance for detailed org list

### PR DESCRIPTION
**Pull request by YodaLightsabr**
- Adds org logo if it exists
- Loads org balance async

w/ @maxwofford

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
Can someone help me figure out why the Rubocop check isn't passing?

image

**Comment by cjdenio** [comment]
For the time being, just wrap it like so:
```ruby
# rubocop:disable Naming/VariableNumber
if Flipper.enabled?(:detailed_events_list_2022_10_04, @current_user)
  @current_user.events.includes(:stripe_cards, organizer_positions: :user)
  # @current_user.events.includes(organizer_positions: :user)
else
  @current_user.events.includes(organizer_positions: :user)
end
# rubocop:enable Naming/VariableNumber
```

I'd be in favor of disabling that rule entirely though

**Comment by YodaLightsabr** [comment]
For some reason this file didn't get picked up with `git add -p`. It's ready for review now.

**Comment by maxwofford** [comment]
`git add -p` only covers partials, not whole new files being checked into git!

**Comment by YodaLightsabr** [comment]
Oh interesting! TIL

**Review by cjdenio — APPROVED** [review]
Looks great!

**Comment by YodaLightsabr** [comment]
*looks both ways\*

**Pull request merged**
