### PR TITLE
Update PVSA Pricing

### PR DESCRIPTION
**Pull request by RhysMP**
Updates promotions screen to reflect updated PVSA price change taking effect 5/01/2024. Please do not merge until then

## Summary of the problem

PVSA Prices are increasing May 1st, promotions pages needs to reflect that

**Do not merge until May 1st!!**

## Describe your changes

Simply changes prices

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]

**Review by YodaLightsabr — APPROVED** [review]

**Review by sampoder — APPROVED** [review]

**Review by garyhtou — APPROVED** [review]
let's make this the most approved pr 😎

**Review by cjdenio — APPROVED** [review]

**Review by malted — APPROVED** [review]
lgtmtbh

**Comment by RhysMP** [comment]
I'm glad everybody approves on the first go. But could everybody take a look again this is a major change which may uhm totally break the code base. @garyhtou

**Comment by YodaLightsabr** [comment]
that's a good point

**Review by YodaLightsabr — DISMISSED** [review]

**Comment by cjdenio** [comment]
merging at rhys's request

**Pull request merged**
