### PR TITLE
[Activity Log] Only render activities if trackable present

### PR DESCRIPTION
**Pull request by faisalsayed10**
Handles trackable items being deleted

- @sampoder

To test:

1) Locally, create a reimbursement report
2) Delete that report
3) Does the homepage render?

### CODE REVIEW

**Comment by jaspermayone** [comment]
Fayd on HCB?

**Comment by sampoder** [comment]
Sam is using Fayd’s laptop

**Comment by jaspermayone** [comment]
Hi Sam and Fayd! 👋🏻

**Comment by sampoder** [comment]
Hi! - Fayd

**Pull request merged**
