### PR TITLE
Add flavor text

### PR DESCRIPTION
**Pull request by YodaLightsabr**

### CODE REVIEW

**Review by sampoder — DISMISSED** [review]
BOOOOOOOOOONNNNNNKKKKKKKKKKKKK!

**Review by garyhtou — DISMISSED** [review]
[_bonk_](https://cloud-3qup26j81.vercel.app/bonk_sound_effect.mp4)

**Comment by sampoder** [comment]
petition to merge

**Comment by sarthaktexas** [comment]
i approve

**Review by sarthaktexas — DISMISSED** [review]

**Pull request merged**
