### PR TITLE
Remove memoization from methods in `Event` that take `start_date` and `end_date` as parameters

### PR DESCRIPTION
**Pull request by sampoder**
We still memo-ize the balance available method, so hopefully we keep most of the benefits of memoization

Closes https://github.com/hackclub/hcb/issues/8128

### CODE REVIEW

**Comment by garyhtou** [comment]
Can you see how this affects loading HQ's transactions and the stripe card approval flow?

I think Rails may chance these repeated queries, but if there's significant degrade in performance, then i'd suggest keeping the memorization:

```ruby
def balance(start_date: nil, end_date: nil)
  @balance ||= {}
  @balance[[start_date, end_date]] ||= begin
    # code
  end
end
```

**Comment by sampoder** [comment]
Do you mean the authorisation webhook?

**Comment by sampoder** [comment]
I'll test them both. The Stripe authorisation flow relies on `balance_available_v2_cents` which is still memoised.

**Comment by garyhtou** [comment]
Got it, okay thanks!

**Comment by sampoder** [comment]
Our SQL queries went from 368 to 369, I think this is good to merge.

**Comment by sampoder** [comment]
I've walked through the Stripe authorisation flow and am confident that we shouldn't see any hits to performance. I'll keep an eye on `#hcb-engr-notifs`.

**Pull request merged**
