### PR TITLE
Hide author column on receipt bin tx rows

### PR DESCRIPTION
**Pull request by malted**
Fixes #7465

### CODE REVIEW

**Comment by garyhtou** [comment]
See https://github.com/hackclub/hcb/issues/7465#issuecomment-2285117567

**Comment by garyhtou** [comment]
We want the partials to not render the author column unless explicitly requested to

**Comment by garyhtou** [comment]
This is because I think the only location where we want the author is on the org ledger, but these partials are used in many other places!

**Comment by malted** [comment]
Just did that!

**Review by sampoder — APPROVED** [review]
LGTM!

**Pull request merged**
