### PR TITLE
Make `a` text color lighter

### PR DESCRIPTION
**Pull request by exu3**

### CODE REVIEW

**Comment by maxwofford** [comment]
Thanks for adding this! How does it look on dark mode?

**Comment by exu3** [comment]
Screen Shot 2021-09-20 at 12 36 39 PM

**Comment by maxwofford** [comment]
Could we go with something a bit more subtle for this one?

**Comment by exu3** [comment]
Screen Shot 2021-09-20 at 1 59 32 PM
Screen Shot 2021-09-20 at 1 59 26 PM

before:
Screen Shot 2021-09-20 at 2 00 48 PM

**Pull request merged**
