### PR TITLE
Remove preload flag for events#show

### PR DESCRIPTION
**Pull request by albertchae**
It looks like the page is the same with or without the flag

```
$ time curl "https://bank.hackclub.com/hq" > nopreload
curl "https://bank.hackclub.com/hq" > nopreload  0.01s user 0.01s system 0% cpu 7.367 total

$ time curl "https://bank.hackclub.com/hq?preload=true" > yespreload
curl "https://bank.hackclub.com/hq?preload=true" > yespreload  0.01s user 0.01s system 0% cpu 2.075 total

$ diff nopreload yespreload

4c4
< <script>window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"NRJS-75b50cf8155b0df9763","applicationID":"807481798","transactionName":"cVpdFxdXW1tWFk5RQVdbRxBKS19YRA==","queueTime":2,"applicationTime":4781,"agent":""}</script>
---
> <script>window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"NRJS-75b50cf8155b0df9763","applicationID":"807481798","transactionName":"cVpdFxdXW1tWFk5RQVdbRxBKS19YRA==","queueTime":3,"applicationTime":1220,"agent":""}</script>
11c11
< <meta name="csrf-token" content="redacted" />
---
> <meta name="csrf-token" content="redacted" />
62c62
<   <a class="header-center text-decoration-none flex items-center false" aria-label="You’re in production mode. You pansy." href="/">
---
>   <a class="header-center text-decoration-none flex items-center false" aria-label="You’re in production mode. Now go write some code?" href="/">
2868c2868
<   <a rel="next" class="btn" href="/hq?page=2">Next &rsaquo;</a>
---
>   <a rel="next" class="btn" href="/hq?page=2&amp;preload=true">Next &rsaquo;</a>
2872c2872
<   <a href="/hq?page=35">Last &raquo;</a>
---
>   <a href="/hq?page=35&amp;preload=true">Last &raquo;</a>
```

So the only differences are
- New Relic timer
- CSRF Token (redacted in above block)
- Random message after "You're in production mode"
- Pagination links adding ?preload=true

I've seen ranges from 5-7 seconds for no preload and 1.5-3s for preloading.

### CODE REVIEW

**Comment by garyhtou** [comment]
heck yeah! smart way of checking for differences too :)

**Comment by albertchae** [comment]
@garyhtou yes! honestly I'm still hoping to make it faster although we're probably close to diminishing returns...

**Review by maxwofford — APPROVED** [review]
LGTM!

**Comment by albertchae** [comment]
I regret not thinking of asking whether we had an APM setup earlier, but for reference here's what it looked like before and after this was deployed
image

The green section second from the bottom for the canonical_pending_transaction partial gets significantly smaller and more consistent after May 2, which is when this PR was deployed.

**Pull request merged**
