### PR TITLE
Add WebP Buildpack

### PR DESCRIPTION
**Pull request by sampoder**
## Summary of the problem

We can't convert WebP images with imagemagik!

## Describe your changes

Takes the same approach as #3366 to add support for converting WebP images.

### CODE REVIEW

**Comment by garyhtou** [comment]
I just wanted to verify with you that webp currently isn't working on staging. Because looking this comment (https://github.com/hackclub/hcb/issues/4034#issuecomment-1615283439) there's a chance the heroku-22 upgrade might have fixed it for staging (and not prod)

**Comment by sampoder** [comment]
Is staging back up? I remember it wasn't possible to sign into it for a while

**Comment by sampoder** [comment]
Doesn't it look like it is, that said we don't seem to have the HEIC buildpack in `app.json` anymore

**Comment by maxwofford** [comment]
cc'ing @albertchae for context on HEIC and WebP support

**Comment by albertchae** [comment]
The HEIC buildpack was removed from `app.json` in https://github.com/hackclub/hcb/pull/4011. You can read that PR for more details, but TL;DR using the heroku-22 stack means we don't need an explicit buildpack anymore.

Unfortunately I think I forgot about upgrading prod to heroku-22 which we were tracking in https://github.com/hackclub/hcb/issues/3398. This is probably something we can do soon.

There also appears to be some more divergence between review apps and prod after https://github.com/hackclub/hcb/pull/4304/files, which calls `config.load_defaults 7.0` in `config/application.rb`, but sets `config.active_storage.variant_processor = :mini_magick` in `config/environments/production.rb`. This means prod is using imagemagick [but all other environments will be using vips](https://guides.rubyonrails.org/configuring.html#default-values-for-target-version-7-0).

So some action items we should take:
- [x] Finalize upgrading prod to heroku-22. https://github.com/hackclub/hcb/issues/3398
- [ ] Decide on imagemagick or vips everywhere and modify the config to reflect that. I am unclear on vips support for HEIC or webp and unclear on whether the imagemagick from heroku-22 handles webp. We should research that too. We should favor using vips since it's supposed to be faster unless there's a compatibility issue
- [ ] ~~This is orthogonal, but do we have an issue for the review app login issue? I'm in some slack DMs related to it, but we should bring the conversation to github.~~ created https://github.com/hackclub/hcb/issues/4927

**Comment by maxwofford** [comment]
Thanks for adding the context @albertchae! @sampoder are you interested in taking on fully switching to VIPS and checking compatibility?

@albertchae Please create a ticket for that review app issue, I don't think I have much context to that.

**Comment by sampoder** [comment]
Sure thing! I can work on the VIPS stuff

**Comment by sampoder** [comment]
To check VIPS support, we could upload HEICs / WebPs to a review app. Am I right in saying that @albertchae?

**Comment by albertchae** [comment]
> To check VIPS support, we could upload HEICs / WebPs to a review app. Am I right in saying that @albertchae?

@sampoder sorry for the late reply but yeah that should be sufficient. I'll work on fixing staging in https://github.com/hackclub/hcb/issues/4927 and ping you afterwards

**Comment by albertchae** [comment]
@sampoder new review apps should be able to login again via email, SMS login is still in progress though

**Comment by sampoder** [comment]
Awesome!

**Comment by sampoder** [comment]
Upgrading to `heroku-22` worked!

**Comment by garyhtou** [comment]
amazing!

**Pull request closed without merging**
