### PR TITLE
Deprecate `StripeAuthorization` jobs

### PR DESCRIPTION
**Pull request by sampoder**
@maxwofford alongside deleting the file and the only call made to it (from what can I see), is there anything else needed to fix #4039?

### CODE REVIEW

**Comment by cjdenio** [comment]
We also have to remove references to the `StripeAuthorization` model, for example, it's still used to calculate the amount spent on a card: https://github.com/hackclub/hcb/blob/105bb2fbf9bc39422a7ef180cbb020e0ba0ebeae/app/models/stripe_card.rb#L136-L138

**Comment by sampoder** [comment]
gotcha! on it!

**Review by cjdenio — APPROVED** [review]
Thanks! ~~Let's see what this breaks~~

**Comment by sampoder** [comment]
hell yeah

**Pull request merged**
