### PR TITLE
Links for specific FAQ items

### PR DESCRIPTION
**Pull request by cjdenio**
👋 Hellooooo bankers! This li'l PR adds some handy links for sharing specific FAQ items (e.g. https://bank.hackclub.com/faq#international-projects). Meant to act as an alternative to [posts like this](https://hackclub.slack.com/archives/CN523HLKW/p1631201753073600?thread_ts=1631200917.069000&cid=CN523HLKW) that either screenshot or quote the FAQ.

Screen Shot 2021-09-09 at 11 27 07 AM

### CODE REVIEW

**Comment by maxwofford** [comment]
This is amazing. What needs to happen for us to merge this?

**Comment by kunalbotla** [comment]
We might want to hold off on this for a bit since we're working on a new FAQ / help section in the dashboard.

**Comment by maxwofford** [comment]
@kunalbotla is that a code change or a copy change?

**Comment by kunalbotla** [comment]
A code change; the new one will be more like a help center with tiles under a tab like the `Documents` section. @eilla1 has more details on how it'll look.

**Comment by kunalbotla** [comment]
We could still push this in since its already made and wouldn't conflict with the new one. It just might be very short lived...

**Comment by garyhtou** [comment]
Yeah, let's hold off on merging this for now. Thanks for the PR @cjdenio. really appreciate it!

**Comment by maxwofford** [comment]
Just talked to @MelSmith104 about the resource page implementation-- looks like FAQ may be moved, but will still have it's own page. Would love to see this feature added in if you're still up for it @cjdenio.

**Comment by maxwofford** [comment]
If you have to update the branch, please rebase rather then update through github so we can avoid extra merge commits

**Comment by cjdenio** [comment]
Helloooooo so what needs to be done on this?

**Comment by maxwofford** [comment]
I just tested in development and it works great. it'd be cool if clicking on the link icon would copy the URL. can you take that on @cjdenio?

**Comment by cjdenio** [comment]
All set!

https://user-images.githubusercontent.com/34525547/135022574-e5a4b166-e32c-4824-ba1f-8964c6b05592.mov

**Comment by maxwofford** [comment]
So great, thank you so much!

**Comment by maxwofford** [comment]
@cjdenio do you want to ship this? it's super dope & I bet the people in the #bank channel would love it

**Comment by cjdenio** [comment]
lol absolutely!

**Pull request merged**
