### PR TITLE
🖼️ Add event logo upload thing

### PR DESCRIPTION
**Pull request by cjdenio**
https://user-images.githubusercontent.com/34525547/178289208-1e6dc61d-d6a8-4648-9ff1-f3f521eb2529.mov

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
_yabadabadoo!_

I'm so happy we'll have this– we can do some really cool stuff in the API + hackathons.hackclub.com once we have it on file. I'm cool with this for the donation page UI b/c the code is good. A couple additional comments...

- Maybe we can even show the logo in place or near the bank logo in transparency mode! Love all the places this can be used.
- It's funny the background image is edited directly on the page, but this is on the edit page
- What sizes am i allowed to post? Does it have to be a square?

**Comment by cjdenio** [comment]
giphy



- Hack yeah!
- Yeah, true. I think the logo should be editable from both the settings page and the donation page, since it'll be used in other places.
- You can upload anything, but you're _supposed_ to upload a square. Bank won't try to constrain it to a square, it'll just constrain the height of the image.

**Review by exu3 — APPROVED** [review]
Hooray, this logo thing is neat!

**Comment by cjdenio** [comment]
https://user-images.githubusercontent.com/34525547/178315813-42cf24d2-953a-43c9-b4c2-9df1016e4b8f.mov

**Pull request merged**
