### PR TITLE
Let users choose a per-session login preference

### PR DESCRIPTION
**Pull request by cjdenio**
This makes it easier for users who want to use Touch/Face ID on one device, while receiving login codes on another.

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
This is great!

**Review by garyhtou — APPROVED** [review]
love this!

**Review by maxwofford — APPROVED** [review]
This looks awesome! Make sure to show @zachlatta!

**Comment by cjdenio** [comment]
Zach's seen it!

Screen Shot 2022-07-25 at 10 39 23 AM

**Pull request merged**
