### PR TITLE
Fix bug where it was using the wrong id when referencing stripe cards

### PR DESCRIPTION
**Pull request by clarencejychan**
Bug fix for #1935 

Transparency mode
image

Logged In w/ No Cards
image

Logged In w/ Cards
image

### CODE REVIEW

**Comment by clarencejychan** [comment]
The `XXXX` seems to be something to do with formatted card numbers but this isn't in the scope of this change. @tanatorn  is this something you need to address?

**Comment by clarencejychan** [comment]
Looks like its coming from `def stripe_obj` under `sripe_card`. Seems like it's not related to this change though.

**Review by exu3 — COMMENTED** [review]
Screen Shot 2021-11-02 at 11 18 59 AM
For some reason I'm getting the heroku error on the cards page in staging (maybe it's my school's internet filters?idk) but it seems to be working fine in development. Thanks for fixing it!
Screen Shot 2021-11-02 at 11 25 02 AM

**Review by maxwofford — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
