### PR TITLE
Revert 1876 heroku conditional signin

### PR DESCRIPTION
**Pull request by exu3**
reverting this to be able to revert #1877

### CODE REVIEW

**Comment by kunalbotla** [comment]
I think we'll only need #1877 reverted. Is GitHub letting you do that or do we need to revert #1876 first?

**Comment by kunalbotla** [comment]
Reverting so that we can revert #1877 without error from GitHub.

**Comment by maxwofford** [comment]
Heads up you can revert commits directly on the command-line for fine control over what's being changed. ex `git revert d41112a315f14b92194c36e7041399a527396378`. When you click the "revert" button on github, under the hood github is running that command on each commit in a PR.

**Comment by exu3** [comment]
Oh I wasn't aware that was possible; I'll keep that in mind next time. thanks for the info!

**Pull request merged**
