### PR TITLE
Use Apple Maps for maps via `maps.hackclub.com`

### PR DESCRIPTION
**Pull request by sampoder**
Screenshot 2024-02-21 at 7 45 12 PM

### CODE REVIEW

**Comment by garyhtou** [comment]
so 🆒❗

**Comment by garyhtou** [comment]
What are some good things to know about that API?
- Does it have a rate limit?
- Does it use an API Key?
- Is there an associated repo?

it might be nice to comment some info above that url

**Comment by sampoder** [comment]
Added!

**Review by garyhtou — APPROVED** [review]
we love 

**Pull request merged**
