### PR TITLE
Emburse cards look like real Emburse cards

### PR DESCRIPTION
**Pull request by maxwofford**
ezgif com-video-to-gif

### CODE REVIEW

**Comment by maxwofford** [comment]
sorry, that was the low-quality gif– uploading the high rez one in a sec

**Review by tmb — APPROVED** [review]
this is awesome lol

**Comment by maxwofford** [comment]
here it is:
ezgif com-resize

**Comment by thesephist** [comment]
Woah. Coming soon: Emburse cards so real you can just reach into the screen and pull it out instead of waiting on the mail.

**Pull request merged**
