### PR TITLE
Make WebAuthn login less confusing

### PR DESCRIPTION
**Pull request by cjdenio**
https://github.com/hackclub/bank/pull/2479#issuecomment-1102852022

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Thanks for adding this! Just want to check– does this handle the case of a user having SMS auth setup? If so, go for merge! If not, could we redirect to SMS auth first for users that have opted-in?

**Comment by cjdenio** [comment]
Currently the priority is WebAuthn -> SMS -> Email; are you thinking that SMS should have higher priority over WebAuthn?

**Comment by maxwofford** [comment]
Ah, think i misread the `form` tag change– looks good for me!

**Comment by cjdenio** [comment]
Great, thanks!

**Pull request merged**
