### PR TITLE
Add blank slate text for cards page

### PR DESCRIPTION
**Pull request by exu3**
This PR adds bblank slate text to the cards page for when there are no cards. 
Screen Shot 2022-01-28 at 12 38 52 AM

Reflects the style of the blank slate text on the receipts page when there are no missing receipts. For reference:
Screen Shot 2022-01-28 at 12 38 55 AM

### CODE REVIEW

**Comment by garyhtou** [comment]
just wondering, what does it look like if you use `blankslate` helper

```
<%= blankslate "message here" %>
```

**Comment by exu3** [comment]
https://github.com/hackclub/bank/pull/2273/commits/398b869b5bc8528d22d2df7a6341f18759632b1c: 

Screen Shot 2022-01-28 at 1 34 50 AM
Screen Shot 2022-01-28 at 1 34 45 AM

**Comment by garyhtou** [comment]
hm i think the left alignment that you originally had might look slightly better here (as long as it's using the same font styling as the blankslate helper), but up to you! good to merge whenever ur ready

**Review by garyhtou — APPROVED** [review]

**Comment by exu3** [comment]
Screen Shot 2022-01-28 at 10 50 32 AM

Screen Shot 2022-01-28 at 10 51 43 AM
Screen Shot 2022-01-28 at 10 51 36 AM
Screen Shot 2022-01-28 at 10 51 28 AM

For the "no missing receipts" case, what if we did something like Slack where they show some flavor text if you have 0 unreads :P

**Comment by garyhtou** [comment]
omg yes i love that idea

**Pull request merged**
