### PR TITLE
Mark "processed" deletion requests as such

### PR DESCRIPTION
**Pull request by cjdenio**
This little change makes it so processed deletion requests are marked with "Organizer deleted" instead of just "Closed".

Screen Shot 2022-05-31 at 12 25 52 PM

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
LGTM!

**Comment by cjdenio** [comment]
Gonna merge this– operations people, feel free to yell at me if you don't like it

**Comment by maxwofford** [comment]
Please post in slack so the ops team sees! They don't all get notifications for GH

**Comment by maxwofford** [comment]
Also, great work improving this. Every touch helps!

**Pull request merged**
