### PR TITLE
Make transparency mode the default when creating new Organizations

### PR DESCRIPTION
**Pull request by exu3**
This PR adds a checkbox to the new event creation form for transparency mode that is checked by default but can be unchecked as needed.

Screen Shot 2022-09-29 at 10 51 23 AM

### CODE REVIEW

**Comment by maxwofford** [comment]
Is this change for admins or user-facing?

**Comment by hackliv** [comment]
This looks good to me! It may be helpful to have a sort of reminder on the user's side when they join, but Mel and I will make sure to share in calls that it will default be on.

**Review by hackliv — APPROVED** [review]

**Comment by exu3** [comment]
> Is this change for admins or user-facing?

The changes in this PR are just on the admin new event form.

**Comment by sampoder** [comment]
Screenshot 2022-10-06 at 11 02 51 PM

Should this be removed alongside this change?

**Comment by maxwofford** [comment]
I just created https://github.com/hackclub/bank/issues/3101 to track the higher-level task here so we don't have to block this PR. @exu3 if the ops team is good with this, go for merge.

**Comment by exu3** [comment]
Approved by Mel on Slack

**Pull request merged**
