### PR TITLE
Fix event deletion

### PR DESCRIPTION
**Pull request by tmb**
fixes #69

### CODE REVIEW

**Comment by zachlatta** [comment]
- What happens to all the linked records?
- Change to archiving events w/ visual indicator and interface changes for Michael.
- No real changes for users besides visual changes

**Comment by lachlanjc** [comment]
@tmb Can you address these this weekend?

**Comment by tmb** [comment]
yup, this was a bigger thing than I thought. I want to get @zachlatta's thoughts on what Michael and I came up with before proceeding so I can make sure this was done correctly. also need to sync with you @lachlanjc about visual changes. [attaching notes from Michael & my call yesterday.](https://www.notion.so/3-15-19-5f4bb69dc46144868385c0c6f3fb863b)

**Comment by lachlanjc** [comment]
@tmb Is this still happening? If it’s not our new roadmap, let’s either get it shipped quickly or close it for now.

**Comment by zachlatta** [comment]
We talked about changing this from "deleting events" to "suspending events", as we'll still need events in our database and viewable even if they're no longer working with us for future records.

I think we should add this to roadmap, after ACH and check sending. @tmb, can you add it to the projects board?

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by tmb** [comment]
closing because this is from Jan. and again I don't know what i was doing. adding this into Ideas for now, we can talk about whether it should be roadmap on next call

**Pull request closed without merging**
