### PR TITLE
[Stripe Card Shipping] Make the user mention white

### PR DESCRIPTION
**Pull request by sampoder**
Fixes https://github.com/hackclub/hcb/issues/5757.

### CODE REVIEW

**Review by sarthaktexas — DISMISSED** [review]

**Review by malted — DISMISSED** [review]
The rest of the text still stays dark

**Comment by malted** [comment]
Before:
image

After:
image

(Also, used `smoke` instead of `white`.

**Comment by malted** [comment]
They look like different shades because the mention text's weight is comparably too light.
~~Also, the baselines are different~~ Fixed

**Comment by sampoder** [comment]
thanks Ben!

**Pull request merged**
