### PR TITLE
Upgrade Ruby from 2.7.5 to 2.7.7

### PR DESCRIPTION
**Pull request by northeastprince**
It seems like it's just fixes and patches, so it's a pretty safe upgrade. Hopefully we can progressively get to the latest version after this.

https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released
https://www.ruby-lang.org/en/news/2022/11/24/ruby-2-7-7-released

### CODE REVIEW

**Comment by northeastprince** [comment]
@cjdenio I don't have access to Heroku so I can't see what's going on with the failed deployment.

**Comment by northeastprince** [comment]
Oh, nvm - I was confused by the deployment error UI segment and thought it had still failed.

**Comment by cjdenio** [comment]
@northeastprince the failed deployment was an app size issue:
Screenshot 2023-02-27 at 5 20 59 PM

**Comment by northeastprince** [comment]
Ah, ok - what are the main causes of the big build size? Also, is that what is preventing the upgrade?

**Comment by northeastprince** [comment]
cc @maxwofford I know you talked to me a little about this when I was being onboarded but I didn't quite understand it

**Comment by northeastprince** [comment]
Build size? 😟

**Comment by northeastprince** [comment]
@cjdenio is this good to merge?

**Comment by maxwofford** [comment]
@northeastprince This looks good! I'm happy with it now that deploys are working. Merging now while I'm online so I can keep an eye on it and any errors that might get flagged. Let's def shrink the buildsize in the near future to prevent this!

p.s. sorry for the slow responses on PRs this week

**Pull request merged**
