### PR TITLE
Removes PVSA perk deadlink

### PR DESCRIPTION
**Pull request by aramshiva**
Closes #4727. Removes deadlink of PVSA perk.

### CODE REVIEW

**Comment by aramshiva** [comment]
Brought over commits from #4702. Weird.

**Review by sampoder — APPROVED** [review]
Perfect; thank you so much!

**Comment by sampoder** [comment]
@aramshiva I think that's because you're using the `main` branch on your fork

**Review by garyhtou — APPROVED** [review]
thank you!

**Pull request merged**
