### PR TITLE
Redo ESLint Setup & Improve IDE error tracking

### PR DESCRIPTION
**Pull request by manuthecoder**
# Summary
This PR properly sets up ESLint so that it properly reports errors in an IDE.

1. Upgrades ESLint version to `9x`
2. Adds devlarations for global variables such as `$`, `BK`, and more
3. Fixes eslint-reported bugs, formats UI.js using existing prettier options, and unused variables across files

### CODE REVIEW

**Comment by sampoder** [comment]
FYI after running `bin/lint`:

Screenshot 2024-08-03 at 4 30 34 PM

**Comment by manu-gurudath** [comment]
yikes - thanks for letting me know!

**Comment by manu-gurudath** [comment]
this should work. try running `yarn install` if you haven't already (this is because the version is upgraded)

image

**Review by sampoder — APPROVED** [review]
Oh sweet, I got this working locally!

**Pull request merged**
