### PR TITLE
Don't Fallback for Amazon SES Emails

### PR DESCRIPTION
**Pull request by sampoder**
https://hackclub.slack.com/archives/C026RKHLPNJ/p1709661775585849

### CODE REVIEW

**Comment by garyhtou** [comment]
@sampoder I haven't taken a close look at this, but I'm fairly certain the emails are due to Hackathons Backend and not HCB

**Comment by sampoder** [comment]
Oh interesting, yeah you're right

**Comment by sampoder** [comment]
Wait we actually probably still want this for HCB

**Comment by garyhtou** [comment]
I'm a bit confused. are these SES emails being directed to hcb@hackclub.com by ActionMailbox? Or, are they being sent directly to hcb@hackclub.com (or hackathon@hackclub.com) by SES?

**Comment by sampoder** [comment]
Not the current ones causing issues, but if one of our email bounces (that we sent from ActionMailer) it would bounce to `@hcb.hackclub.com`? Idk maybe I'm missing smth and Rails automatically handles those

**Pull request closed without merging**
