### PR TITLE
[MarkdownService] Only attempt a user-autolink if `@record` is defined

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by sampoder** [comment]
https://hackclub.slack.com/files/USNPNJXNX/F06T45NG6CU/screenshot_2024-04-05_at_10.49.32___am.png

**Review by garyhtou — CHANGES_REQUESTED** [review]
I think we should rescue instead. Some policies may allow for a `nil` record

**Comment by sampoder** [comment]
My understanding is that 

Pundit.policy(u, @record)

is looking for the policy related to @record & then checking if u has access. So the bug here was that if @record was nil, we don't have a policy for nil items

**Comment by garyhtou** [comment]
ah shit, right

**Pull request merged**
