### PR TITLE
[User Feedback] Add top text to discourage using feedback form for support

### PR DESCRIPTION
**Pull request by rluodev**
## Summary of the problem
Users may have thought the feedback form was the support form, and were filling it to get support.

## Describe your changes
Added a header to the input text field that lets users know that, if they're looking for help, they should contact hcb@hackclub.com.

Screenshot 2024-05-01 at 10 06 40 PM

light mode

Screenshot 2024-05-01 at 10 06 18 PM

dark mode

### CODE REVIEW

**Comment by sampoder** [comment]
Let's shorten it to one line:

`Looking for support? Email us.`

**Comment by rluodev** [comment]
> Let's shorten it to one line:
> 
> `Looking for support? Email us.`

Updated!

**Comment by sampoder** [comment]
I changed the styling a bit, I thought what we previously had... whilst very nice, looked like a header for the form input.

**Review by sampoder — APPROVED** [review]

**Comment by rluodev** [comment]
@sampoder do you have a pic of the updated styling

**Comment by sampoder** [comment]
Screenshot 2024-05-02 at 10 57 17 AM

**Comment by rluodev** [comment]
oh perfect, looks great!

**Comment by garyhtou** [comment]
thanks!

**Pull request merged**
