### PR TITLE
Hot Hot Fix Exports

### PR DESCRIPTION
**Pull request by sampoder**
## Summary of the problem

Simple variable name problem that got missed, sorry!

### CODE REVIEW

**Comment by garyhtou** [comment]
https://github.com/hackclub/bank/blob/3d9b0b41164211c8b2727c87f799f6a3001a0369/app/controllers/exports_controller.rb#L69 has a bug

image

Instead of `current_user.email`, it should be `params[:email]`.

Can we please test PRs before assigning for review? Thanks!

**Comment by garyhtou** [comment]
Also, let's find a way to DRY up this controller action (can you please handle this in a separate PR?)

https://github.com/hackclub/hcb/issues/4597

**Comment by sampoder** [comment]
Mb, sorry I was creating this on my phone! Let me test rq

**Comment by garyhtou** [comment]
Also, the `Ledger` export does not behave the same as the other formats. Can you update the `redirect_back` to match the other's `redirect_to`?

https://github.com/hackclub/bank/blob/036654f7143f54d2de2225c2935b7836d32bb7c2/app/controllers/exports_controller.rb#L71

**Comment by sampoder** [comment]
alright i've tested this twelve cases which all seem to work

epoch `.json` not signed in
epoch `.csv` not signed in
epoch `.ledger` not signed in

epoch `.json` signed in
epoch `.csv` signed in
epoch `.ledger` signed in

hq `.json` not signed in
hq `.csv` not signed in
hq `.ledger` not signed in

hq `.json` signed in
hq `.csv` signed in
hq `.ledger` signed in

**Comment by sampoder** [comment]
i'm not able to load `/hq` locally when signed in (it just loads for ever, smth for me to fix later myself) but i tested them by going to http://localhost:3000/exports/hq.json etc.

**Review by garyhtou — APPROVED** [review]
ty for doing such a thorough test!

**Pull request merged**
