### PR TITLE
End grace period for receipt attachments through old HMAC codes

### PR DESCRIPTION
**Pull request by northeastprince**
Completes #3959.

### CODE REVIEW

**Comment by northeastprince** [comment]
Should be good to merge, but if someone can remove the unneeded credentials beforehand that'd be great.

**Comment by cjdenio** [comment]
@garyhtou/@northeastprince: is this ready to merge?

**Comment by northeastprince** [comment]
Should be, as soon as someone removes the credentials.

**Comment by northeastprince** [comment]
Looks like there are merge conflicts - you have to merge main and then remove it.

**Review by cjdenio — APPROVED** [review]

**Pull request merged**
