### PR TITLE
Remove hacks unneeded after Ruby 3 upgrade

### PR DESCRIPTION
**Pull request by albertchae**
- Remove default gems that are no longer needed with ruby 3 upgrade (see https://github.com/hackclub/bank/pull/3448 for context)
- Remove default suffix: false to silence ruby 3 keyword argument warnings (see https://github.com/hackclub/bank/pull/3898 for context)

### CODE REVIEW

**Comment by northeastprince** [comment]
When I looked at this PR based on the title I expected to find something along the lines of "remove Ruby 3 preparations, don't need that version anyway 😤" 💀

**Comment by albertchae** [comment]
@northeastprince oh sorry this was supposed to be a draft PR but I think hackclub's github account wasn't allowing drafts at the time. The title just came from the branch name which is `gh`'s default behavior IIRC

**Comment by albertchae** [comment]
@maxwofford in accordance with the PR experiment we discussed on Tuesday June 13, I consider this PR low risk and you can merge after approving.

**Comment by maxwofford** [comment]
Merging now while staying near my computer so I can monitor the deploy

**Pull request merged**
