### PR TITLE
Improve money inputs

### PR DESCRIPTION
**Pull request by manuthecoder**
This PR addresses #7235 and improves money input functionality, including reimbursement amount inputs. It fixes this by selecting all the text inside an input field if the value matches "0.00"

Closes #7235

### CODE REVIEW

**Comment by sampoder** [comment]
Would it be possible for us to go with the focus-ing implementation?

**Comment by manu-gurudath** [comment]
done!

**Comment by sampoder** [comment]
Let's just do this for the reimbursement expense form, I think that's the only that has issues

**Comment by manu-gurudath** [comment]
> Let's just do this for the reimbursement expense form, I think that's the only that has issues

fixed!

**Review by sampoder — APPROVED** [review]

**Pull request merged**
