### PR TITLE
(WIP) Add new virtual card background

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
Before
Screenshot 2020-03-14 17 40 25

After
Screenshot 2020-03-14 17 36 05

**Comment by thesephist** [comment]
LGTM! Thanks.

**Review by thesephist — APPROVED** [review]
🌟

**Comment by maxwofford** [comment]
Ah, heads up this was intended as a WIP (work in progress) & wasn't ready for merge (see #553)

**Comment by thesephist** [comment]
Ah whoops, somehow my eyes glossed right over the WIP. My bad. I'll revert.

**Pull request merged**
