### PR TITLE
Add badge to changelog button

### PR DESCRIPTION
**Pull request by cjdenio**
Adds a tiny Headway widget to the changelog button! (https://docs.headwayapp.co/widget)

https://user-images.githubusercontent.com/34525547/158658321-af01bbcd-71f1-49b5-8c8c-8eff02ff494a.mov

(looks like the badge can be totally hidden in the settings)

Screen Shot 2022-03-16 at 2 16 44 PM

(possibly closes #2376)

### CODE REVIEW

**Comment by exu3** [comment]
Hooray, thanks for adding this Caleb! 

I think we're going to delay on merging this for a little bit until we update the changelog history to fill in the 2-year time gap between Stripe cards and SMS login ship. This is so that people don't get spammed with slightly outdated/irrelevant changelog notifications after the changelog badge/widget feature gets shipped.

**Comment by maxwofford** [comment]
Is there a way to set the default "last read at" timestamp? Another option is to set the read at to today, and then the next log we publish will start the count at "1". I just want to prevent a situation where it says "4 unreads", but the user has already seen them.

**Comment by maxwofford** [comment]
Oh, does this sync between sessions? If i click it on mobile, will the notice still show on laptop?

**Comment by maxwofford** [comment]
We now have [4](https://changelog.bank.hackclub.com/know-your-merchant-229142) [semi](https://changelog.bank.hackclub.com/user-feedback-229335)-[recent](https://changelog.bank.hackclub.com/face-id-fingerprints-yubikeys-oh-my!-228110) [changelogs](https://changelog.bank.hackclub.com/sms-login-codes-224029) in our list– want to merge this?

**Comment by cjdenio** [comment]
This is all ready for merge whenever you'd like to– first, you should just set "expire badge count" option to 10 or so to prevent old items from showing up as unread (I think)

Screen Shot 2022-04-21 at 10 48 23 AM

**Comment by maxwofford** [comment]
Just updated. Will merge and deploy now!

**Pull request merged**
