### PR TITLE
Initial implementation of universal ID

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
What is this/why are we implementing it?

**Comment by maxwofford** [comment]
@lachlanjc I was playing around with this back when we did transparency mode. A bunch of our routes depend on private info (ex. how certain transactions have the bank account number in the URL). This would implement a universal ID that we could use for everything by default

**Comment by motdotla** [comment]
@maxwofford and @lachlanjc you might find Rails' Global IDs interesting for this use case as well. They are sort of a hidden secret built into Rails.

https://mikerogers.io/2019/08/03/using-signed-global-id-in-rails.html

**Comment by lachlanjc** [comment]
Are we still moving forward on this?

**Comment by motdotla** [comment]
I'd personally like to table this for now and close the PR. I think we can better address after the transaction engine.

Thoughts @maxwofford  ?

**Comment by maxwofford** [comment]
Yep! Closing

ezgif com-gif-maker

**Pull request closed without merging**
