### PR TITLE
Fix canceled unactivated Stripe Card status

### PR DESCRIPTION
**Pull request by sampoder**
Closes https://github.com/hackclub/hcb/issues/8753, thanks reporting Luke!

### CODE REVIEW

**Comment by Luke-Oldenburg** [comment]
Do we want to leave the "Card for X is on the way!" message even after it has been cancelled?

**Comment by Luke-Oldenburg** [comment]
re: my last comment, if HQ has shipping info then maybe there could be a "Card for X has arrived!" message instead.

**Comment by sampoder** [comment]
Re both comments: if the card is cancelled or activated, we should probably hide that message

**Comment by sampoder** [comment]
We don't have tracking

**Comment by Luke-Oldenburg** [comment]
Will do :+1:

**Pull request merged**
