### PR TITLE
Open the floodgates of WebAuthn

### PR DESCRIPTION
**Pull request by cjdenio**
🌊🔒

### CODE REVIEW

**Comment by maxwofford** [comment]
Let's also remove the "Beta" pill on the settings page.

**Review by maxwofford — APPROVED** [review]
I'm cool with this merging! Please update the indentation of the chunk of code though

**Comment by maxwofford** [comment]
Related to https://github.com/hackclub/bank/issues/2387

**Comment by cjdenio** [comment]
Turns out checking "Ignore whitespace in diff editor" in VS Code was a bad idea after all

**Pull request merged**
