### PR TITLE
Install `rubocop-rails`!

### PR DESCRIPTION
**Pull request by cjdenio**
## Summary of the problem

linters are exciting! i wish we had more linters.

## Describe your changes

This adds the `rubocop-rails` plugin, which introduces a bunch of rules that identify Rails specific problems & deprecation. Not all of these rules are helpful, but many are useful for fixing common performance and consistency issues.

### CODE REVIEW

**Comment by garyhtou** [comment]
yeahhhhhh!

**Comment by garyhtou** [comment]
lint
image

**Comment by cjdenio** [comment]
EXACTLY

**Comment by cjdenio** [comment]
I'd love a second pair of eyes on this once I fix the failing CI

**Comment by sampoder** [comment]
linters 😍🤩💖

**Pull request merged**
