### PR TITLE
Decrease compression on receipts

### PR DESCRIPTION
**Pull request by sampoder**
Fixes #4476

### CODE REVIEW

**Comment by sarthaktexas** [comment]
lgtm

**Review by northeastprince — APPROVED** [review]
Make sure to confirm the example is fixed in staging before merge.

**Comment by sampoder** [comment]
Staging is broken atm, specific example works in dev though.

**Review by YodaLightsabr — APPROVED** [review]

**Review by garyhtou — APPROVED** [review]
imma trust that this works haha

**Comment by sampoder** [comment]
~~only one way to find out~~

**Pull request merged**
