### PR TITLE
Add copy for `cash_withdrawals_not_allowed` declining

### PR DESCRIPTION
**Pull request by sampoder**
Screenshot 2024-08-07 at 4 19 30 PM

The account had 5k in it but cash withdrawals were disabled.

Interestingly the bank had this error message:

Screenshot 2024-08-07 at 4 22 39 PM

### CODE REVIEW

**Comment by garyhtou** [comment]
lol i love the IRL testing

**Comment by sampoder** [comment]
i've been to every ATM in Shelburne at this point! one guy gave me a funny look after i was happy that my card declined

**Comment by garyhtou** [comment]
hahah

**Comment by garyhtou** [comment]
hack club hq atm when?

**Comment by sampoder** [comment]
Please

**Pull request merged**
