### PR TITLE
DRY up Gemfile by getting the current Ruby version from .ruby-version

### PR DESCRIPTION
**Pull request by northeastprince**

### CODE REVIEW

**Comment by albertchae** [comment]
FYI I think this broke running `./docker_setup.sh`. I see this error when running that script now

```
 > [13/17] RUN bundle install:
#0 0.314
#0 0.314 [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /usr/src/app/.ruby-version. Bundler cannot continue.
#0 0.314
#0 0.314  #  from /usr/src/app/Gemfile:6
#0 0.314  #  -------------------------------------------
#0 0.314  #
#0 0.314  >  ruby File.read(File.join(File.dirname(__FILE__), ".ruby-version")).strip
#0 0.314  #
#0 0.314  #  -------------------------------------------
------
failed to solve: executor failed running [/bin/sh -c bundle install]: exit code: 4
```

**Comment by northeastprince** [comment]
Sorry about that @albertchae - can you try putting `ADD .ruby-version /usr/src/app/.ruby-version` right after `ADD package.json /usr/src/app/package.json` and tell me if that fixes it? If so, I'll open a PR adding that change.

**Comment by northeastprince** [comment]
Update: successfully replicated the issue with a full image rebuild and fixed it in #3557.

**Comment by albertchae** [comment]
@northeastprince thanks! I verified your PR fixed it

**Pull request merged**
