### PR TITLE
Re-enable comment version history UI

### PR DESCRIPTION
**Pull request by maxwofford**
This is a WIP, it should support edge cases like the new `has_untracked_edit` boolean that comments have.

### CODE REVIEW

**Comment by maxwofford** [comment]
@exu3 could i get your review on this? Trying to add similar functionality to GitHub's edit history (see https://github.com/hackclub/bank/pull/2206#issuecomment-1023329590 as an example of a comment with edit history).

Not sure if this is good enough to merge, but I also don't know what it's still missing.

**Review by exu3 — COMMENTED** [review]
I think this looks really neat! This UI feels pretty good overall.

A couple things I noticed:

- The "user is admin" / "it's you!" tooltip gets clipped.
  - Screen Shot 2022-02-11 at 01 50 13
- For the "Copy link" anchor link, it'd be nice to have a tooltip & "Copied link :tada:"-type confirmation message similar to the FAQ page. I'm not sure if this feature was originally on this branch; I think it might've been added or edited when this branch was updated with `main`.
  - Screen Shot 2022-02-11 at 01 54 31
- At first glance, it felt a bit weird that the comment boxes didn't span the full width
  - Screen Shot 2022-02-11 at 02 00 23

**Comment by maxwofford** [comment]
@exu3

- Comment boxes now span the full width
- That functionality was there before, but noone know about it. This highlights the feature, and I agree it'd be nice to have a click & copy interaction. I'd like to not require that for merging this though.
- the "admin"/"you" tooltip is now not being clipped

Cool if this is merged?

**Comment by exu3** [comment]
Looks great! Cool to merge.

**Pull request merged**
