### PR TITLE
Use `stripe_obj&.shipping&.tracking_number&.present?`

### PR DESCRIPTION
**Pull request by sampoder**
Should fix the new bug.

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
\*blindly approving prs\*

i _trust_ you and caleb

**Comment by sampoder** [comment]
still testing before i merge

**Comment by sampoder** [comment]
Screenshot 2024-02-21 at 8 01 34 PM

works on an erroring card

**Comment by garyhtou** [comment]
It looks like this broke things in development. When the Stripe API doesn't work, `stripe_obj` returns a Hash, which we can't call methods on.
https://github.com/hackclub/bank/blob/f5ccd23350132916b9220075bf3f63eb65800eb5/app/models/stripe_card.rb#L226

I'd suggest converting that Hash into a [`Struct`](https://ruby-doc.org/core-2.5.1/Struct.html)

**Pull request merged**
