### PR TITLE
Include event name and ID in Stripe Invoice footer

### PR DESCRIPTION
**Pull request by garyhtou**
_Not tested!_

## Before
(set as default footer in Stripe)
image (23)

## After

This should override the default footer setting in Stripe to allow for customized footers per invoice (including event name and ID). New footer:

```
Need to pay by mailed paper check? You can mail checks to:

Hack Club HQ (#183) c/o The Hack Foundation
8605 Santa Monica Blvd #86294
West Hollywood, CA 90069
```

<br/>

---

**I have changed the default footer in Stripe settings to:**

```
Need to pay by mailed paper check? You can mail checks to:

[Name of Organization] c/o The Hack Foundation
8605 Santa Monica Blvd #86294
West Hollywood, CA 90069
```

### CODE REVIEW

**Comment by garyhtou** [comment]
Should line 298 be `self.sponsor.event.name`?
https://github.com/hackclub/bank/blob/ca92de27907c18886fefd42f3167a488dc3f275e/app/models/invoice.rb#L297-L302

**Review by iamcpdev — CHANGES_REQUESTED** [review]
Hey this won't work in production check out how you're formatting the ERB tag

**Comment by iamcpdev** [comment]
Remove the double hash mark

**Comment by iamcpdev** [comment]
@garyhtou you need to define event.id

**Comment by iamcpdev** [comment]
[Invoice-EF6638C3-0001.pdf](https://github.com/hackclub/bank/files/6040247/Invoice-EF6638C3-0001.pdf)

Tested this. Should work fine. Good job!

**Review by iamcpdev — DISMISSED** [review]

**Pull request closed without merging**
