### PR TITLE
Enforce consistent double quotes for strings

### PR DESCRIPTION
**Pull request by northeastprince**
This should be the same across all strings unless there is a need to escape certain characters, [per the Ruby Style Guide](https://rubystyle.guide/#consistent-string-literals) and numerous other sources for conventions and best practices.

Besides `rubocop.yml`, all other files were not touched manually and only through RuboCop automatically fixing applicable strings (`rubocop -a`).

### CODE REVIEW

**Comment by maxwofford** [comment]
@northeastprince looks fine, but please request after the tests are passing! Also in the future I'd recommend putting the config change in it's own commit separately so it's easy to track down.

**Comment by northeastprince** [comment]
Yeah, I didn't realize ERB checks run separately and don't get autocorrected by Rubocop, so I'm going through each ERB file to make sure I don't mess up a contraption or anything 😆

**Comment by northeastprince** [comment]
@maxwofford this should be good now, sorry for the preemptive review request.

**Review by maxwofford — APPROVED** [review]
This looks good! Going to cause some extra work for anyone with an open PR though as they rebase, so give a heads up in the slack that this is getting merged and people should rebase at their own discretion.

**Pull request merged**
