### PR TITLE
Redesign account details

### PR DESCRIPTION
**Pull request by malted**
image

### CODE REVIEW

**Comment by jaspermayone** [comment]
@malted is that HCB's prod act number??

**Comment by jaspermayone** [comment]
one should probably remove that if so 👀

**Comment by sampoder** [comment]
I don't think it makes sense to remove them from the main page. This page's primary purpose is for people to see their account and routing number which we seem to have removed. I do like the redesigned modal though!

**Comment by garyhtou** [comment]
> one should probably remove that if so 👀

Thanks Jasper! I've redacted it

**Comment by sampoder** [comment]
I've added them back for now so we can get this in because it looks great, we can put that in another PR if everyone else wants to go for removing them. Not sure what others think

**Review by sampoder — APPROVED** [review]

**Pull request merged**
