### PR TITLE
[Reimbursements] Add the word reimbursement close to the start of the notif email

### PR DESCRIPTION
**Pull request by malted**
image

Not sure if this is the optimal change. Thoughts?

### CODE REVIEW

**Review by sarthaktexas — DISMISSED** [review]
I like this way more

**Comment by garyhtou** [comment]
Please add to email subject too!

**Comment by garyhtou** [comment]
I'd also suggest moving the name of the report to the end of the subject in case it's really long

**Review by sarthaktexas — APPROVED** [review]

**Review by sarthaktexas — DISMISSED** [review]
We need to change the format of all of them.

**Comment by garyhtou** [comment]
Yes please!

**Review by sampoder — APPROVED** [review]

**Pull request merged**
