### PR TITLE
Rename from if to admin_only

### PR DESCRIPTION
**Pull request by rluodev**
Screenshot 2024-01-26 at 5 34 36 PM

It is now renamed to be more intuitive

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]

**Review by sarthaktexas — APPROVED** [review]

**Review by sampoder — COMMENTED** [review]
Thoughts on `admin_only_if`? Just want to make it clear that it expects a conditional

**Comment by garyhtou** [comment]
maybe "admin_when"

**Comment by cjdenio** [comment]
Or maybe a separate `admin_tools_if` helper, similar to Rails's `link_to_if`?

**Comment by sampoder** [comment]
I think that's the best idea so far

**Comment by garyhtou** [comment]
yeah! great idea. let's do that!

**Comment by garyhtou** [comment]
unrelated: it would be nice to drop the `s`. `admin_tool` >>> `admin_tools`

**Review by garyhtou — APPROVED** [review]
good to merge after someone gets a second eye on this

**Review by sarthaktexas — APPROVED** [review]

**Pull request merged**
