### PR TITLE
Upgrade to Rails 7.1

### PR DESCRIPTION
**Pull request by cjdenio**

### CODE REVIEW

**Comment by garyhtou** [comment]
OHHHHH YES PLEASE 🙏

**Comment by cjdenio** [comment]
This should be ready to go. Two caveats:

- I had to remove the `skylight` gem to prevent a weird version conflict. I assume we're not using it regularly and can try to add it back later.
- This upgrade **will log every HCB user out**. I'm not sure why (looks like they changed the format/algorithm for encrypted cookies), and I can't find anything in the documentation on how to prevent this. It's annoying, but I don't think users will care. (anyone is welcome to look into fixing this)

**Comment by sampoder** [comment]
sorry that's my bad re: the AdminMailer! i wonder why that only just starting breaking now?

**Comment by cjdenio** [comment]
For posterity: the logout issue was was found to only affect development

**Pull request merged**
