### PR TITLE
Use `@inbound_mail&.mail&.subject` and then have a fallback

### PR DESCRIPTION
**Pull request by sampoder**
This makes progress towards fixing https://github.com/hackclub/hcb/issues/5286. I think that one issue might be us adding a new subject (this shouldn't break it... the `In-Reply-To` header should just work! but no Gmail!) so I've made it so that we only use the custom subjects as fallbacks.

@cjdenio thoughts? Was there a reason you avoided doing this in https://github.com/hackclub/hcb/pull/4786. 

Also, does anyone know, is there a cleaner way to do this?

### CODE REVIEW

**Comment by garyhtou** [comment]
Would the stuff we learned about `thread_id` and `references` headers help here?

**Comment by sampoder** [comment]
We should certainly do that! Let's put it in a separate PR though

**Comment by sampoder** [comment]
I'm going to try this out, if it doesn't fix the bug in Gmail I'm going to revert it

**Comment by garyhtou** [comment]
Great! I do think we should still implement `thread_id` and `references` headers regardless

**Pull request merged**
