### PR TITLE
Re-organize Admin Dashboard

### PR DESCRIPTION
**Pull request by exu3**
take a look at comment [#1185800043](https://github.com/hackclub/bank/pull/2715#issuecomment-1185800043) for the final version –@kunalbotla.

Initial pass on re-arranging the dashboard based on feedback from @hackliv:

Screen Shot 2022-06-23 at 3 15 45 PM

### CODE REVIEW

**Comment by hackliv** [comment]
hell ya!!

**Review by hackliv — APPROVED** [review]

**Comment by kunalbotla** [comment]
image


`Tasks & Perks` are tasks that have a goal of being at 0; they're organized by similar types of actions rather than the backend organization.

`Information` is frequently accessed information. 

`Admin Tasks` has automated or infrequently used admin tools.

`Other Tools` has other tools using the old admin system.

`Information (old)` has admin tools using the old admin system with a substitute newer tool.

**Comment by hackliv** [comment]
Can we move the top row of "Information" to be "Ledger" then "Organizations" the "Users" ("Pending Ledger" underneath "Ledger")

**Comment by kunalbotla** [comment]
> Can we move the top row of "Information" to be "Ledger" then "Organizations" the "Users" ("Pending Ledger" underneath "Ledger")

image

done!

**Review by hackliv — APPROVED** [review]

**Comment by MelSmith104** [comment]
This looks great! the only extra suggestion i'd have is i'd prefer ledger to be under tasks - we have a goal of that being zero every day as well other than that it looks good to go!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
